### ISSUE TITLE
Design Structure and Content Validation.

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#100]
Define all requirements to be able to perform structure and content validation on all Case Notification messages - Old MMGs (pre GenV1), GenV1, GenV2 summary and case, condition-specific, multiple conditions, FDD specific scenario of Foodnet vs FoodBorne networks.

**Comment by mscaldas2012** [comment]
Structure Validation will solely be based on simple IGAMT profiles that validates messages against PHIN SPECS. 

The validator can simply look at MSH-21[1] and a matching profile must exists to validate the message structurally. - If no profile exists, the message needs to be dead lettered.

If any Structure errors exists - the message will be flagged as invalid and will not be futher processed.

------

For Content/MMG validation, it becomes trickier. A Message can be solely based on GenV2 (MSH-21[2], or it can be based on GenV2 + specific condition/event Codes MMG - MSH-21[3]. Also, some programs have "multiple tabs" MMGs, i.e., MMGs that differentiate between different conditions/event Codes (OBR-31.1)

The full set of different use cases are: (all explained in detail later)
* GenV2 messages
* GenV2 + Program MMG messages
* GenV2 + Program MMG + Condition specific MMG
* FDD - special case of states in Foodnet network sending different messages than other STLTs

A table will need to be maintained in order to map how a message should be validated against a MMG. Different MMG-AT profiles will need to be available for all possible combinations.
Also, with the advent of future GenV3 and others, GenV2 will be validated separately from the condition specific MMG and the reports consolidated.
Ex.: A message comes with the following MSH-21:
**NOTF_ORU_v3.0**^PHINProfileID^2.16.840.1.114222.4.10.3^ISO~**Generic_MMG_V2.0**^PHINMsgMapID^2.16.840.1.114222.4.10.4^ISO~**FDD_V1.0_MMG_MVPS_TR_20180316**^PHINMsgMapID^2.16.840.1.114222.4.10.4^ISO

* NOTF_OUR_v3.0 - is used on Structure Validation against Phin Spec 3.0 specification.
* Generic_MMG_VV2.0 - is used on MMG Validation against the GenV2 MMG-AT specification
* FDD_V1.0_MMG_MVPS_TR_20180316 - is further used on MMG Validation against that MMG-AT specification.


**`TBD: It's been discussed whether PHinSpec 3.x are all backwards compatible. If that is the case, we will validate all 3.X PhinSpec against the latest one (3.1 today, 3.2 as soon as that is completed)`** 

Because FDD is one of the programs that has multiple tab MMGs, the condition specific MMG will be used.

Ex.: For the message above, the OBR-31 is **11020^Campylobacteriosis^NND**

Therefore, a MMG-AT profile must exist for **FDD_V1.0_MMG_MVPS_TR_20180316_11020**

FDD also has a very specific requirement where they differentiate two STLT networks: Foodnet and FoodBorne. Foodnet is a network of 10 states that are required to send extra information along with their messages and therefore they are required to use a different MMG Guide.

We will identify this difference for FDD, by looking at the reporting Jurisdiction (OBX[@3.1='77968-6']-5.1). If that value is one of the 10 Foodnet states, we will use FDD_V1.0_MMG_MVPS_TR_20180316_11020**_Foodnet** guide. Otherwise, we will use the normal guide.

**Comment by lmcnabb** [comment]
I think this is fine as written but am editing to add in info on GenV1 and legacy MMGs.  
I think we need a master mapping table for all of this don't you?
