### ISSUE TITLE
Create 1 page SharePoint site summary for DEX project

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#104]
The DEX team will require a variety of static sites.

| Audience | Site | 
|------------|-----|
| CDC Int | SharePoint site |
| Public | General public website on cdc.gov | 
| STLTs | Dev Portal > Submission APIs | 
| CDC Int > Programs | Dev Portal > Consumption APIs |
| Public | Status page, e.g., statuspage.io |

Create the initial CDC Int[ernal] SharePoint site for DEX. The other sites are out of scope for this issue.

**Comment by rmharrison** [comment]
Draft verbiage: 2022-09-16 DEX Verbage.docx

**Comment by rmharrison** [comment]
We have a new home page: https://cdc.sharepoint.com/teams/CDC-Data-Exchange

@jmann2817 Feel free to edit, then move to Done.

**Comment by jmann2817** [comment]
Looks good. Do we want to add a section for contributing partners?
