### ISSUE TITLE
Convert Legacy MMG CSV to MMGAT JSON format

### ISSUE THREAD

**Issue by marcia-schulman** [CDCgov/data-exchange-hl7#108]
Previous title of this isssue: Build Legacy MMGs in IGAMT
However, Legacy MMGs all use PHINSPEC 2.0 for their NIST IGAMT.

Legacy: 8
| Program | MMG Version | PHINSPEC Version | Note | 
|-----------|-----------------|---------------------|-------|
| Arboviral | 1.2.0 |	2 |	These will not come in with GenV1 or GenV2	
Arboviral	| 1.3.0 |	2 |	These will not come in with GenV1 or GenV2	
Arboviral	| 1.3.1 |	2 |	These will not come in with GenV1 or GenV2	
Arboviral	| 1.3.2 |	2 |	These will not come in with GenV1 or GenV2	
Tuberculosis | 2.0.3 |	2 |	These will not come in with GenV1 or GenV2	
Varicella	| 2.01 |	2 |	These will not come in with GenV1 or GenV2	
Varicella	| 2 |	2 |	These will not come in with GenV1 or GenV2	
Varicella	| 1 |	2 |	These will not come in with GenV1 or GenV2

**Comment by mscaldas2012** [comment]
Issue above is resolved.
