### ISSUE TITLE
building/deploying vocab function in Terraform'd function app - debugging with storage/vault/insight

### ISSUE THREAD

**Issue by boris-ning-usds** [CDCgov/data-exchange-hl7#109]
I built a function app using Terraform and Neelima and I found out that it's not quite right.

This issue is to track tasks needed for building and deploying the vocab function in a Terraform function app. 
The vocab app is a cron job that runs periodically (once every Friday) as a Azure function, but it doesn't seem to be running, for whatever reason.

Debugging it last Friday, I found out that the `AzureWebJobsStorage` setting within the function app wasn't setting an storage key properly - the function app requires a storage account and access to it for it to work. We may be also missing some basic settings such as Redis function keys within the function.

There's more to debug and I would like to get to a point where manual deployment from Neelima for the vocab functions properly triggers the cron job.

**Comment by rmharrison** [comment]
From Boris...

>I just got out of a meeting with Neelima on switching the vocab cron job (that pushes to Redis); it works and is functional but we found couple problems; and actions on my side.
>
>Action:
>
>1. App Insight Connection String need to be added for all function app, this is needed for single test run while viewing Code + Test. This is easy to do in Terraform and was just a simple oversight on my part.
>
>2. Zscaler access to Redis - SSL handshake problem. Somehow hitting tf-vocab-cache-dev.redis.cache.windows.net on port 6380 incurs a SSL error on the Java code when doing local GFE + Zscaler testing via Neelima's machine. I need to do some investigation to diagnose whether this is a certificate trust (due to Zscaler man-in-the-middle our traffic) or Zscaler is outright blocking our traffic to a private endpoint Redis instance.
>
>3. (Nice to have) Redis Console viewing via console - broken because to private endpoint. Viewing directly into the Redis Console is a "preview" service from Azure, and they never designed (?) it to work when you have private endpoints turned on. The workaround is to write some code to verify that Redis is indeed populated with vocab.
