### ISSUE TITLE
Create a redaction config for the "case notifications" use case

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#111]
Define the fields that we will redact for the HL7v2 case-based surveillance use case (e.g., NNDSS).  They should mostly be in the PID and NK families of segments.  To define this list necessitates reviewing the various versions of PHIN Specs and MMGs to discover the pertinent PID and NK segments to redact and creating that file as a "config".  Each HL7v2 data stream will have it's own redaction config.  Create a redaction config that can be "read" by the redaction function in the pipeline.

**Comment by rmharrison** [comment]
The case redaction config should be the UNION of the data elements in these two files.
- PHIN Spec Unsupported Fields.xlsx
- ELR and Case Redacted Fields.docx

**Comment by marcia-schulman** [comment]
Redaction config file for case
[case_config.txt](https://github.com/CDCgov/data-exchange-hl7/files/10699369/case_config.txt)
