### ISSUE TITLE
Review blanket processing rules in current process

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#113]
Deliverable:

1. Review all the blanket processing rules that MVPS currently applies.  These would be on the first two tabs of the "NND Requirements Implementation Matrix" spreadsheet attached here.

[https://app.zenhub.com/files/510836864/de2a7ee7-2697-4327-abc5-21ecf3062181/download](https://app.zenhub.com/files/510836864/de2a7ee7-2697-4327-abc5-21ecf3062181/download)

2. Compare these business rules to the validation rules/errors/warnings thrown by Structural validator and MMG validator.  Identify the gaps/deltas where we don't have coverage and think/plan on how to integrate that in.

*We should also note that the error/warning messages outlined in this spreadsheet could be used to update the error/warning messages for the structural validator and MMG validator.  <Meaning: re-use the verbiage>  This work should be put on a new issue.

**Comment by marcia-schulman** [comment]
Per our meeting with Erik Knudsen on 12-16-22, we have determined the following:
1. A separate Blanket Processor service is not needed.
2. There are some blanket processing rules that MVPS has implemented that we will not support.
3. There are some blanket processing rules that MVPS has implemented that we have not yet implemented, but will, most of which will be incorporated into the MMG Validator.
The attached spreadsheet details the blanket processing rules and indicates which of the above categories applies to each rule.
[NND Requirements Implementation Matrix - 2022-12-16 DEX.xlsx](https://github.com/CDCgov/data-exchange-hl7/files/10249710/NND.Requirements.Implementation.Matrix.-.2022-12-16.DEX.xlsx)
