### ISSUE TITLE
Using `azcopy login` authentication to copy data to storage 

### ISSUE THREAD

**Issue by raman-cdc** [CDCgov/data-exchange-hl7#117]
Using Azure CLI to copy data to Storage 
- azure-cli for list directory
- azcopy for actually doing the copy

**Comment by rmharrison** [comment]
`azcopy login` works for...
- EDAV Subscription > ADLS General Storage Account
- EDAV Subscription > ADLS DEX Storage Account

`azcopy login` DOES NOT work for. Must use ServicePrincipal or SAS token.
- DEX Subscription > ADLS Storage Account

**Comment by raman-cdc** [comment]
To test azcopy functionality, Sample azcopy.md file is available under  ./doc folder
	•	Purpose of the file
		azcopy.md file is sample file used  to copy data into DEX ADLS storage account using SAS token. 
                Replace the value of  "storage_acc",  "container_name",  and "SAS_TOKEN" and run the command
  
	•	Reference URL to use ADLS copy command. 
		https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10
		
	•	Reference URL to generate SAS tokens
		https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview

	Two sections
	◦	SAS token
			Please see azcopy.md command on how to use SAS Token to copy files
	◦	azcopy login
 	         	Download azcopy
	                 azcopy login	
                                   a. Use a web browser to open the page https://microsoft.com/devicelogin and enter the code <CODE>  to authenticate.
                                    b. Enter your AD username and password to authorize.

**Comment by raman-cdc** [comment]
Service Now ticket "RITM0051053" was created on 9/20/22 and resolved on 9/23/2022
Recommendation was to use SAS token
