### ISSUE TITLE
Research feasibility of adding a Redaction Report to HL7-PET redact functionality

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#118]
Need a report to track what fields where redacted on a given message.
Sometimes, it's easy to determine - simply find the word "REDACTED" on a field. Others, might be more obfuscated, say, PID-5 or when hashing a value. 
Need to determine too if state sent the field REDACTED or our pipeline is modifying the message and redacting locally.

https://github.com/mscaldas2012/HL7-PET

**Comment by rmharrison** [comment]
Waiting on higher priority work, namely moving the pipeline from Storage -to- MMG Validator to the TF cloud.

**Comment by mscaldas2012** [comment]
Ticket reviewed with all developers - Example of a Redacted report:
[
  {
    "path": "PID-11.9",
    "rule": "",
    "lineNumber": 3
  },
  {
    "path": "PV1",
    "rule": "$REMOVE",
    "lineNumber": 4
  },
  {
    "path": "NK1",
    "rule": "NK1|1|REDACTED",
    "lineNumber": 5
  },
  {
    "path": "NTE",
    "rule": "$REMOVE",
    "lineNumber": 6
  },
  {
    "path": "NTE",
    "rule": "$REMOVE",
    "lineNumber": 9
  },
  {
    "path": "NTE",
    "rule": "$REMOVE",
    "lineNumber": 11
  },
  {
    "path": "NTE",
    "rule": "$REMOVE",
    "lineNumber": 12
  },
  {
    "path": "OBX[@3.1='52831-5']-5",
    "rule": "REDACTED",
    "lineNumber": 18
  },
  {
    "path": "OBX[@3.1='77997-5']-5",
    "rule": "REDACTED",
    "lineNumber": 19
  },
  {
    "path": "OBX[@3.1='77993-4']-5",
    "rule": "REDACTED",
    "lineNumber": 20
  },
  {
    "path": "SPM",
    "rule": "$REMOVE",
    "lineNumber": 24
  },
  {
    "path": "SPM",
    "rule": "$REMOVE",
    "lineNumber": 28
  },
  {
    "path": "SPM",
    "rule": "$REMOVE",
    "lineNumber": 44
  },
  {
    "path": "SPM",
    "rule": "$REMOVE",
    "lineNumber": 45
  },
  {
    "path": "SPM",
    "rule": "$REMOVE",
    "lineNumber": 49
  },
  {
    "path": "SPM",
    "rule": "$REMOVE",
    "lineNumber": 57
  }
]
