### ISSUE TITLE
Customer requests "Concept Name" and "Preferred Concept Name" be brought back and appended to message  

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#119]
When performing code + value set lookups using PHIN VADS, the program would like us to bring back the "Concept Name" and "Preferred Concept Name" for each value set in the message from the PHIN VADS lookup and append that to each message.  This issue is for writing the code to pull back that data from the PHIN VADS database and persist it in Redis and to also write the code for pulling back these additional fields, if the code is correct and in the current value set.  

There is a related ticket on where to put this additional data (metadata) once retrieved (e.g., the best way to append this information to the message) and that work will be covered by that ticket.

**Acceptance Criteria**
1. Demonstrate that the HL7v2 pipeline can pull the preferred concept name and concept name values from the PHIN VADS lookup tables, when the code is correct.

Using the Clinical Manifestations value set in the Lyme/TBRD guide as an example:  https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.7840  so that you can see what the "Concept Name" and "Preferred Concept Name" looks like.

**Comment by rmharrison** [comment]
FAQ on 2022-11-23

Q, Cosmin: Only for "coded elements", that is elements that are in PHIN VADS
A, Ryan: Yes, only for coded elements

![2022-11-23 Standup - PHINVADS 2.PNG](https://images.zenhubusercontent.com/62fe6e4e7c59c94524ab80ae/00a9273a-5050-4cf8-ba0c-1178e99510db)
All look ups from PHIN VADS in Redis with jedis.hget()

Step 1. Look up Concept Code in 3.1 to get Value Set
https://phinvads.cdc.gov/vads/SearchAllVocab_search.action?searchOptions.searchText=LAB278

Step 2. Look up Concept Code in 5.1. Use the Preferred Concept Name for the ValueSet
https://phinvads.cdc.gov/vads/SearchAllVocab_search.action?searchOptions.searchText=59250001
