### ISSUE TITLE
MMG Validator: Build MMG Validation Function for HL7 processing pipeline, using Lyme/Arbo test messages

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#133]
Status as of 2023-01-30

| MMG             | MMG Validator tested | Why Missing | 
|-----------------|----------------------|---|
| GenV2 + Lyme    | x |
| GenV2           | x | 
| GenV1-Case      | x | 
| GenV1-Summary   |  |  do not receive (per Marion)
| Legacy Arbo 1.3 | x | 
| Legacy Arbo 1.2 |   | No test messages

**Comment by lmcnabb** [comment]
@marcia can you update the description on this one?

**Comment by rmharrison** [comment]
Moved to review. Pending 376 for closure.
