### ISSUE TITLE
Design a Table to map Event Codes / Conditions for the Hepatitis /Lyme + Arbo MMGs to be used for Validation/Transformation.

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#135]
In Scope
- Updates to "LymeTBRDArboEventCodeMapping.xlsx"
- Arbo/Lyme MMG

Out of scope
- Hep, FDD MMG
- Table in Redis format
- Implementation in MMG Validator service

| Event Code | MMG Name (Key in Redis) | MMG UUID | Program Folder |
| ----------- | ----------- | ----------- | ----------- |
|      "11089"  | -> "LYME"  | MMG UUID | Folder Location
|      "11080"   | -> "TBRD"  | MMG UUID | Folder Location
|      "11088"   | -> "TBRD"  | MMG UUID | Folder Location
|      "11090"   | -> "TBRD"  | MMG UUID | Folder Location
|      "11091"   | -> "TBRD"  | MMG UUID | Folder Location
|     "10250"  | -> "TBRD"  | MMG UUID | Folder Location
and so on...

**Comment by rmharrison** [comment]
Psuedo code from Cosmin...

> We'll need in Redis (I think) a table of : Event Code, MMG Name (key to retrieve it), MMG UUID
> Example on a HL7 message if GenV2, and event code is 11089, then the MMG Validator will apply GenV2 + Lyme MMG rules

```
// Event Code | MMG Name (Key in Redis) | MMG UUID

      "11089" -> "LYME" // | MMG UUID

      "11080" -> "TBRD" // | MMG UUID

      "11088" -> "TBRD" // | MMG UUID

      "11090" -> "TBRD" // | MMG UUID

      "11091" -> "TBRD" // | MMG UUID

      "10250" -> "TBRD" // | MMG UUID

      else -> HL7Error.EVENT_CODE_NOT_SUPPORTED_ERROR.message
```

**Comment by rmharrison** [comment]
@lmcnabb Please add update from Lyme/Arbo.

**Comment by lmcnabb** [comment]
Received spreadsheet back from program on 9.30.2022.  Requires follow up with program epi before proceeding and getting more questions answered.

**Comment by lmcnabb** [comment]
Here is the file received from Karen.  It requires a deeper dive with her team and epis to get some questions answered.  https://cdc.sharepoint.com/:x:/r/teams/CDC-Data-Exchange/Shared%20Documents/Pilot%20-%20HL7%20-%20Lyme%20Arbo/Event%20Codes/LymeTBRDArboEventCodeMapping.xlsx?d=wf369c3760bbd4e708abe24115ff9e7b1&csf=1&web=1&e=a0b8Kt

**Comment by marcia-schulman** [comment]
[StateReportingRouteForDifferentCategoryData.xlsx](https://github.com/CDCgov/data-exchange-hl7/files/9757569/StateReportingRouteForDifferentCategoryData.xlsx)
[LymeTBRDArboEventCodeMapping (1) (1).xlsx](https://github.com/CDCgov/data-exchange-hl7/files/9757570/LymeTBRDArboEventCodeMapping.1.1.xlsx)
Updated information from NCZEID regarding Arbo spec usage (from Craig Mincic)

**Comment by lmcnabb** [comment]
Can you see the diff between 1.3.1 and 1.3.2 next? If it is truly another value set change and that is it.  Then we build out the validation one time and have it validate against all three (1.3.0, 1.3.1, or 1.3.2)

**Comment by marcia-schulman** [comment]
There is no difference between 1.3.1 and 1.3.2. The only revision was on the introductory page in the Resources section. So, we can safely use 1.3.2 for all 1.3.x validation.

**Comment by marcia-schulman** [comment]
This issue is now closed, with the decision to use a namespaced key (with namespace "condition") and a JSON string value that contains all the MMG and program mapping information for the condition.

See "options.txt" referenced above for a full description of the selected option (Option A)

**Comment by marcia-schulman** [comment]
QED

**Comment by marcia-schulman** [comment]
We decided to update the JSON format of the mmg map record to use the profile name (normalized to lower case) as a key to the mmg list. New JSON format is this:

```json
{
    "event_code": "11091",
    "name": "Ehrlichiosis/Anaplasmosis, undetermined",
    "program": "NCEZID",
    "category": "Vectorborne Diseases",
    "mmg_maps": [
        {
            "lyme_tbrd_mmg_v1.0": [
                "mmg:tbrd"
            ]
        }
    ]
}
