### ISSUE TITLE
Phinvads Vocab function enhancements

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#139]
@mscaldas2012 comments....

I was wondering if we can make some changes to Redis PHINVads... 

I'd like to see if you can add the concepts as a map ... like this:
/* Insert name and age field in <hash-1> */Map<String,String> map = new HashMap<String, String>(map.put("concept1",valueConcept1);map.put("cencept2",valueConcept2);jedis.hmset("PHVS_YesNoUnknown", map);

[Yesterday 11:37 AM] Caldas, Marcelo (CDC/DDID/NCEZID/DPEI) (CTR)
with that' I don't even need to download the concepts... I'll be able to use a jedis.hexists("vocabKey", "conceptKey")

**Comment by rmharrison** [comment]
@mscaldas2012 Which PR was this implemented on? (Because I'd like the PR and the issue linked)

**Comment by rmharrison** [comment]
@mscaldas2012 Which PR was this implemented on? (Because I'd like the PR and the issue linked)
