### ISSUE TITLE
Terraform for TST/STAGING/PROD environment for Eventhub

### ISSUE THREAD

**Issue by boris-ning-usds** [CDCgov/data-exchange-hl7#142]
This is related to #54 but I felt the scope for all environments mean I have to setup subnets and privatelinks for all the other infrastructure without knowing how the Dev environment will work for us.

I'm breaking all other environments (Test, Staging, Prod) into this ticket instead.

The configuration outline is as follows from Marcelo.
Config:
- DEV -> Pricing Tier: Basic (no support for capture or retention) $ 11/TU/month #54
- [ ] TST -> Pricing Tier: Std $22 /TU/Month
- [ ] STG -> Pricing Tier: Std
- [ ] PRD -> Pricing Tier: Std

**Comment by rmharrison** [comment]
DEX RG as of 2023-01-30
Done
- DEV
- STG

Not done
- TST
- PRD
