### ISSUE TITLE
Setup CI (Continuous Integration) pipeline

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#146]
**CI pipeline (in parallel)**
- Unit test runner
- Linters
- Code scanners
- Dependency checkers

**Comment by rmharrison** [comment]
## Ryan's preferences...

**CI runner**
Commercial with yaml file
1. Concourse
2. Circle
3. Travis
4. GitHub

Open question: Does OCIO have a preferred runner? Will OCIO allow (1), (2) or (3)?

Commercial with GUI config (doesn't use YAML file in repo)
5. Jenkins

**Code scanners**
1. SonarQube
2. Quality gate (Code smells vs industry)
3. Fortify (Authorizing Official may force us to use)
4. Checkmarx

**Dependency checker**
1. Snyk

**Linters**
CI: ???
Devs: InteliJ Kotlin liner

**Front-end test suite**
1. [Cypress](https://www.cypress.io/)
N. Selenium

**Comment by boris-ning-usds** [comment]
Here's a guide from OCIO on Fortify setup:
https://itguides-cdc.msappproxy.net/source-code/scanningPractices/
