### ISSUE TITLE
parameterize event hub name on functions

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#152]
Need to read event_hub_name form local.settings.json

 @EventHubTrigger(
                name = "msg", 
                // TODO:
               ** eventHubName = "%event_hub_receiver_name%", **
                connection = "EventHubConnectionString") 
                message: String?,
            context: ExecutionContext) {

and on local.settings.json:
...
"Values": {
    "event_hub_receiver_name": "hl7-structure-ok",
...

For functions that use EventHub
- [ ] Reciever-Debatcher
- [ ] StructureValidator
- [ ] MMG Validator

**Comment by rudumas** [comment]
@mscaldas2012  @lmcnabb Would we want to label this a technical debt or Refactoring?
