### ISSUE TITLE
add message_hash as metadata on receiver Fn

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#164]
handled by #191

**Comment by lmcnabb** [comment]
[https://app.zenhub.com/files/510836864/5b1144f7-25a0-4cab-9292-8cfa41bfff84/download](https://app.zenhub.com/files/510836864/5b1144f7-25a0-4cab-9292-8cfa41bfff84/download)

**Comment by mscaldas2012** [comment]
This ticket will be covered by #191, where all metadata is being revamped
