### ISSUE TITLE
Develop Message Transformer for Lake of Segments

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#175]
In order to create a proper Hierarchy of Segments and have that hierarchy derived from Configuration files, I'm requesting the code to use the existing feature in HL7-PET to create such hierarchy tree...

this is accomplished with a single line of code and one config file:

<code>
val treeParser= HL7HierarchyParser.parseMessageHierarchy(message, profile)
</code>

where:

* message is the HL7 Message we're parsing and
*  profile is the configuration of parent/child relationship of profiles.

# Details

- Receives event hub notifications
- ~Selects the right MMG specification~ Not dependent on MMG
- Creates Lake of Segments
- ~Validates content per MMG~ (part of MMG validator)
- ~Validates content per Vocab~ (part of MMG validator)
- Creates and event hub notification

- ~ Integrate to Azure Vault~ Not using Vault
- [x] Integrate to Azure Event Hub: 1 to receive, 2 for send: ok and failure
- [x] Integrate to Azure Monitor Log 
- ~ Integrate to Azure Redis (for MMGs and Vocab)~ Not needed
- [x] Receive JSON message from Event Hub
- [x] Transform Message to Lake of Segments
- [x] Push JSON to Event Hub

**Comment by mscaldas2012** [comment]
Lake of Segments should use a HL7-PET profile config file in order to determine the hierarchy of Segments.

Basic Schema:
``` json
{
   "ref": "{SEG}-99",
   "segment": "...",
   "line_number": 99,
   "parentSegmentRef": "" 
}
``` 

where:
 * ref is a reference to the segment composed of the 3-letter segment name (ex. MSH) and its line Number. ex.: MSH-001
 * segment is the full text of the segment. ex.; MSH|^\&|SYSTID1^2.16.840.1.114222.1234^ISO|GADPH^2.16.840.1.114222.1235^ISO|PHINCDS^2.16.840.1.114222.4.3.2.10^ISO|PHIN^2.16.840.1.114222^ISO|20220909165421||ORU^R01^ORU_R01|123451|T|2.5|||||||||NND_ORU_v2.0^PHINProfileID^2.16.840.1.114222.4.10.3^ISO~Gen_Case_Map_v1.0^PHINMsgMapID^2.16.840.1.114222.4.10.4^ISO
 * lineNumber is the line number where the segment is found on the full HL7 message
* parentSegmentRef is the reference of the parent segment (according to the basic profile below). Ex.: for MSH, it will be NULL, all other segments will have a parentSegmentRef - MSH-001


The basic profile to use is as follow:
``` 
MSH
  |--> PID
         |--> NTE
         |--> PV1
         |--> NK1
  |--> ORC
  |--> OBR
          |--> OBX
                 |-->NTE
          | --> SPM
                  |-->OBX
           |--> NTE

```

**Comment by cosmycx** [comment]
Lake of Segments concept:

Proposal 1: (keeps full lineage to parents with data, flat, more disk space but simple)

[
[ MSH , PID , OBR (1) , OBX ],
[ MSH , PID , OBR (1) , OBX ],
[ MSH , PID , OBR (1) , OBX ],

[ MSH , PID , OBR (1) , OBX ],
[ MSH , PID , OBR (1) , OBX ],
[ MSH , PID , OBR (2) , OBX ],
[ MSH , PID , OBR (2) , OBX ],

OBR
NTE:
[ MSH , PID , OBR (2) , NTE ],

OBR
OBX
NTE:
[ MSH , PID , OBR (2) , OBX , NTE ],

[ MSH , PID , OBR (2) , SPM ],
[ MSH , PID , OBR (2) , SPM ],
[ MSH, PID, NTE ]
]

---------------------------------------
Proposal 2: (only with reference to parent, nested, less disk space but complex)

[

[ MSH_001, MSH ],
[ PID_002, *MSH, PID ]
[ *PID , OBR (1) ],
....

----------
Proposal 1 accepted for current development.

**Comment by cosmycx** [comment]
New function started with event hubs, stub out transformer and tree model. ( PR #476 )
TODO: read tree in json, use hl7-pet, and flat the segments model ( postponed right now due to other sprint goals)
