### ISSUE TITLE
Databricks: summary view for Structure Validator and MMG Validator result

### ISSUE THREAD

**Issue by rudumas** [CDCgov/data-exchange-hl7#178]
Build Validation Reports for Structure and MMG Validation issues according to lucd chart https://lucid.app/lucidchart/c756c505-7678-4964-ab00-8565062af81e/edit?invitationId=inv_b7117784-e14d-439a-b716-c1aecb93df15&page=_BAer_.WH7f5#

- [x] Use LakeConfig. #410 
- [x] Review columns on bronze table (ex.: Struct Report should be process)
- [x] Update raw table names.
- [x] Update bronze table names.

## Stretch goals
- [ ] Silver tables
- [ ] Gold Tables/View (depending on routing)

![image](https://user-images.githubusercontent.com/3239945/207911221-52e69e89-2fef-4f56-bab6-809a51665e71.png)

**Comment by rudumas** [comment]
this is a

**Comment by rudumas** [comment]
@lmcnabb I can now edit the description however unable to edit further... any suggestions?

**Comment by raman-cdc** [comment]
Flattened Structure Error table to list repeating blocks  values

**Comment by rmharrison** [comment]
Outcome from cdcgov/data-exchange-hl7-dbx v0.0.3
- Created Databricks bronze tables from Event Hubs Delta table for after applying MMG Model for Structure Validation.
- Flattened Structure Error table to list repeating blocks
- Modified Bronze tables to read as stream on top of Delta tables for live update.
- Created view in Databricks combing Structure Error and Structure Ok messages into a single view
v_hl7_structure_bronze_stream
- Created Databricks Dashboard/Visuals for Structure Validation

**Comment by raman-cdc** [comment]
Use LakeConfig is complete

**Comment by raman-cdc** [comment]
Created Summary View for Structure Validator and MMG validator

<img width="1205" alt="Screenshot 2022-12-29 at 7 19 42 PM" src="https://user-images.githubusercontent.com/97614308/209962820-bc523eaf-5f35-4aca-b521-c4d8fb1642cb.png">

<img width="1139" alt="Screenshot 2022-12-29 at 7 21 35 PM" src="https://user-images.githubusercontent.com/97614308/209963029-d87d34ec-e71b-4829-b3be-16cbb600255b.png">
