### ISSUE TITLE
Plan for how to incorporate blanket processing rules into pipeline

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#196]
The product owner with Erik Knudsen (SME) and the HL7 development team went through the analysis results that Marcia compiled in response to evaluating the NNDSS requirements spreadsheet.  

Results of meeting were:
There aren't enough blanket processing rules to justify a separate service.
The blanket processing rules that we will apply can be incorporated into the MMG validator service.
The blanket processing rules that we are going to incorporate into the MMG validator service are the following:

<List here>

**Comment by lmcnabb** [comment]
@marcia-schulman @mscaldas2012 I just edited the parent epic for this and associated issues.  Can someone add the list of what we are going to include here or attach abbreviated spreadsheet?

**Comment by marcia-schulman** [comment]
The decisions are in this spreadsheet:[NND Requirements Implementation Matrix v3 - 2022-12-16 Decisions](https://cdc.sharepoint.com/:x:/r/teams/CDC-Data-Exchange/Shared%20Documents/Pilot%20-%20HL7%20(Lyme,%20Arbo,%20Hepatitis)/MVPS/NND%20Requirements%20Implementation%20Matrix%20v3%20-%202022-12-16%20Decisions.xlsx?d=wb247b466aa5246949b46a00f59001c9d&csf=1&web=1&e=mhLZVh)

The TL;DR is we will implement 2 rules in the MMG Validator:
1. The combination of the data element identifier (OBX-3) and the observation sub id (OBX-4) must be unique.
2. OBX-4 (Observation Sub-ID) MUST be populated for data elements in a repeating group.
