### ISSUE TITLE
All functions using Redis to acquire configuration 

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#209]
SHALL
- Use TF Redis

Functions
- [x] MMG Validator
  - [x] MMG Redis Table
  - [x] Vocab Redis Table 
- [X] Vocab Function @dtx0111 
- [X] MMG Validation Function @dtx0111 
  - [X] load MMGs from MMG AT 
  - [x] #223  load Legacy MMGs 
- [x] Message Transformer > MMG-based model transformer 2022-12-01 @dtx0111 Confirm this is done in the transformer

N/A
- Receiver-Debatcher
- Structure Validator

**Comment by boris-ning-usds** [comment]
I vote for a 5 for points (since I'll be missing standup Oct 21).
From my understanding, Redis is already terraformed with a private endpoint ready to go. We can also test locally because the local firewalls via zscaler has also been completed. If I have time, I'll probably use this ticket as part of setting up my development environment locally on my GFE.

**Comment by boris-ning-usds** [comment]
I spent the latter half of my day setting up my GFE and writing test code for firewall testing.

**Comment by boris-ning-usds** [comment]
This has been an integration task for hl7 application developers to use Redis - Redis has been spun up for a while now; and the team has been slowly integrating with it as they see fit. 

This is no longer an infrastructure task. Removing infrastructure tag.

**Comment by boris-ning-usds** [comment]
This has been an integration task for hl7 application developers to use Redis - Redis has been spun up for a while now; and the team has been slowly integrating with it as they see fit. 

This is no longer an infrastructure task. Removing infrastructure tag.

**Comment by rmharrison** [comment]
2022-12-12: @dtx0111 confirmed she completed this task last sprint. No associated PR; rather, checking that each Function consumed from Redis.
