### ISSUE TITLE
Blanket processing error & warning text - review, edit, and update

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#219]
Include in error & warning, text that is readable and understandable by a lay person.  If possible, include exact error and warning language that MVPS uses.

**Comment by marcia-schulman** [comment]
Leslyn and I decided to leave the PHIN Spec validator messages as-is for now, pending feedback from programs. A separate issue is to determine which messages are ERRORS vs. WARNINGS, so we will create a separate issue for that.
