### ISSUE TITLE
DEX use EDAV > Databricks for DEV

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#24]
## Status of ADLS connections to EDAV Databricks
- [x] DEX Subscription ADLS
  - [X] 2022-10-03: DSO_DEX_Cluster_Python_SQL_AD
  - [X] DSO_DEX_Cluster_AD_ACLs_Disabled
  - [X] DSO_DEX_Cluster_AD_ACLs_Disabled_Test
  
- [x] 2022-09-28: EDAV Subscription ADLS > DEX Storage account 
- [x] 2022-09-19: EDAV Subscription ADLS > General Storage account (where DEX is at container/folder ocio/dso/dex) 

NB: All ADLS StorageAccounts are DEV, not PROD.

## Additional notes
In September 2022, DEX was forced to opt for "Option 3" using StorageAccounts and Databricks hosted by EDAV (see figure in #45).

#71 tracks EDAV StorageAccounts for DEX.
This issue tracks EDAV Databricks for DEX.

Meetings
- [X] 2022-09-19

**Comment by raman-cdc** [comment]
EDAV created 2 DBR clusters
1. OD_OCIO_DSO_DEX_Cluster_Python_SQL_AD Cluster
2. OD_OCIO_DSO_DEX_Cluster_AD_ACLs_Disabled

We were able to connect to DEX Storage Acc (ocioededatalakedbr) using  OD_OCIO_DSO_DEX_Cluster_Python_SQL_AD Cluster, but could not find out how this cluster is connecting to Storage Account.

We need to understand how this cluster is connecting to DEX ADLS to manage it better.


As a followup on 10/4/22, EDAV team is creating a new DBR cluster for DEX team to connect to DEX Storage account and possible delete other 2 clusters.

**Comment by raman-cdc** [comment]
EDAV created new Databricks cluster - DEX_Cluster_Python_SQL_AD and asked us to use this.

Validated access to  EDAV storage for DEX from above cluster

**Comment by raman-cdc** [comment]
Updated Cluster names on the top

Validated access to DEX and EDAV Storage accounts from Databricks for all 3 cluster
