### ISSUE TITLE
Security coordination for ATO process

### ISSUE THREAD

**Issue by boris-ning-usds** [CDCgov/data-exchange-hl7#242]
I started skimming through what we'll need in terms of an Authority to Operate (ATO) process, including the Risk Management Framework (RMF), security controls and what we can inherit from.

I would like to start re-drawing our boundary diagrams, and document our access controls on particular setup, including coordination needed with CSPO to get us our ATO in a timely manner.

This ticket is written with some open-endedness in mind, as it is not yet clear to me what needs to be done - and we don't have a lot of guidance on this topic as of late.

**Comment by boris-ning-usds** [comment]
This work is being transferred over to @ChrisB-16 for creating a "CR".

**Comment by lmcnabb** [comment]
Reviewed and provided comment on BSI
