### ISSUE TITLE
Integrate Hepatitis MMG into Pipeline

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#248]
Intent: The HL7v2 case pipeline should work for Hep, end-to-end...
- Hep MMGs dropped in S3 bucket
- Structure validation
- MMG validation
- Transforms
  * Segments
  * MMG-based
  * MMG-in-SQL
-  Views in Databricks

Tasks
- [x] Update MMGs in prod with PHIN spec numbers spreadsheet (https://cdc.sharepoint.com/:x:/r/teams/CDC-Data-Exchange/_layouts/15/Doc.aspx?sourcedoc=%7B14BDEEA7-0C0E-4423-916F-61DDE58E3A02%7D&file=MMGs%20in%20prod%20with%20PHIN%20Spec%20numbers%20(8.19.2022).xlsx&action=default&mobileredirect=true).

**Comment by RuDue** [comment]
@marcia-schulman @lmcnabb Is this EPIC Completed; should we close this Epic?

**Comment by lmcnabb** [comment]
@marcia-schulman  - is there anything in the transform part (the three data models) that will have to be done especially for Hep since it has dynamic identifiers?  If it doesn't have to be treated differently in the transform process then I would say, yes, we could close but I defer to Marcia.
