### ISSUE TITLE
Sync MMG Validation Report to be more closely to NIST Structure Report.

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#267]
Would like to make both validation reports - MMG and Struct a little more similar.
- [x] MMG Report needs summary of counts and status
- [x] use same property names (use struct names)
    - [x] struct.description vs mmg.message
    - [x] struct.path vs mmg.hl7path
    - [x] struct.line vs mmg.lineNumber
    - [x] struct.classification vs mmg.category
    - [x] struct.category vs mmg.type
    
the MMG report seems to have two redundant fields - errorMessage and type - they seem to convey the same info. might want to remove one

**Comment by RuDue** [comment]
Validated as undertstoo 11/9 backlog grooming with @mscaldas2012  who has f/u with Ryan
