### ISSUE TITLE
MMGAT function - push result array to Redis

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#280]
MMGAT API, on endpoint getGuideById, Instead of storing all json into redis, store result array for a key.

**Comment by marcia-schulman** [comment]
We also need to remove the extraneous sections from the bottom of the MMG. Nothing after "blocks" should be included. 
Please remove the sections circled in the image.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/111081583/200685210-f007b302-7645-46bc-9ecd-4266b92d9690.png)
