### ISSUE TITLE
Develop Receiver-Debatcher Code and Function 

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/data-exchange-hl7#29]
- Receives event hub notifications
- Reads (from) JSON notification
- Creates message (file) metadata
- Debatches files into HL7 messages
- Creates and event hub notifications for ok and for failure

- Saves metadata to a database for later replay
- Integrates replay functionality

- [x] Integrate to Azure Blob
- [x] Integrate to Azure Event Hub: 1 to receive, 1 for send: ok
- [x] Receive JSON message from Event Hub
- [x] JSON message to class
- [x] Reads blob storage file 
- [x] Debatch HL7 file into messages
- [x] Design HL7 message metadata (class) of file metadata + message metadata
- [x] Metadata/s to JSON
- [x] Push to Event Hub ok messages

---
Moved to issue #78 
-  Integrate to Azure Vault
-  Integrate to Azure Monitor Log 
-  Push to Event Hub failure messages
-  Change Event Hub push to batch push for performance
---
-  Integrate to Azure selected database solution (other issue)
-  Design and develop message (file) Replay functionality

**Comment by rmharrison** [comment]
Closed with PR #79
