### ISSUE TITLE
Add Gen V2.0.1 to MMGAT legacy method.

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#294]
Download  Gen V2.0.1.json from MMGAT API & upload into legacy_mmgats folder under MRR, to load into Redis.

**Comment by marcia-schulman** [comment]
Can you please name the redis key with the same name as the profile that appears in the HL7 message? That would be like this:

    mmg:generic_mmg_v2.0

Please leave the "." in there
