### ISSUE TITLE
Discovery and planning for how to include the lab template into the two data models

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#307]
Customer need:  As a customer, I need to access lab template data that will sometimes come in as part of messages from some, but not all senders.

Development need: We need to incorporate the NNDSS lab template into two of DEX's data products:
- MMG-based
- MMG-in SQL

------
Background:
There are two use cases for downstream customers (programs) where they can receive data that will not undergo MMG validation.  How do we push additional segments into all models, where sometimes these segments can be expected to some degree (lab template) and unexpected in other scenarios?  These two scenarios are the lab template **AND** segments not specified in the MMG.  Both uses cases will undergo redaction and structural validation.  However, there will be nothing in the MMG validation step for these two use cases because the lab template will not be included in MMG validation and some segments may come in that are not defined in the MMG.  In addition, both scenarios may have repeats at an element level and repeats within repeats (lab template).

We need to figure out how to provision that information to the programs using our three models:  Lake of OBX, MMG-based data model, and Normalized SQL tables.

**Acceptance Criteria** 
1. A STLT user sends in the lab template appended to a message.  Those lab template segments pass through redaction and validation services.  Error and warning metadata applied in same manner as rest of the message.  There is nothing in the MMG to validate against with these additional lab template elements.  The lab template segments should carry on through and be provisioned to the customer with the rest of the message.  For the three models this means that:

- Lake of OBX model - nothing to be done, the segments exist in the lake, linked with the rest of the message

- MMG-based model - the model needs to expect arrive al of the lab template or additional segments (not specified in the MMG) arriving on any given condition's message.  The lab template in places can repeat at the element level and block level an unknown number of times.  Expect that additional unspecified segments that may arrive will do the same.  The developers will need to build the capability to accept the lab template or segments not specified in the MMG, into the model somewhere and it can account for varying number of repeats (TBD).  

- Normalized SQL model - the model needs to expect arrive al of the lab template or additional segments (not specified in the MMG) arriving on any given condition's message.  The lab template in places can repeat at the element level and block level an unknown number of times.  Expect that additional unspecified segments that may arrive will do the same.  The developers will need to build the capability to accept the lab template or segments not specified in the MMG, into the model somewhere and it can account for varying number of repeats (TBD).

**Comment by mscaldas2012** [comment]
Based on the Lab Template Spreadsheet, here's how we can map lab templates on the models:
**Note: Schema_comments are just to provide comments for readability, they are not part of the final generated schema"**
``` json
{
  "schema_comment": "//For each LAB OBR in a message, you'll have one Lab order:",
   "lab_orders": [ 
      {
		"place_order_number": "OBR-2 ",
		"filler_order_number": "OBR-3",
		"test_ordered_name": "OBR-4",
		"observation_datetime": "OBR-7",
		"specimen_action_code": "OBR-11",
		"ordering_provider": "OBR-16",
		"results_status_change": "OBR-22",
		"result_status": "OBR-25",
		"parent_result": "OBR-26",
		"parent_lab_order": "OBR-29",
		"reason_for_study": "OBR-31",
		"parent_universal_service_identifier": "OBR-50",
        "schema_comment": "//For each OBX within this OBR",
		"tests_results": [ 
			{
			"test_performed_name": "OBX-3",
			"observation_subid": "OBX-4",
              "schema_comment": "//OBX-5, //different types (OBX-2) will have different test_results.",
			"result": { }, 
			"units_of_measure": "OBX-6",
			"result_range": "OBX-7",
			"interpretation_flag": "OBX-8",
			"result_status": "OBX-11",
			"specimen_collection_date": "OBX-14",
			"test_method": "OBX-17",
			"specimen_analyzed_date": "OBX-19",
			"performing_lab_name": "OBX-23",
			"performing_person_name": "OBX-25",
			"comments": "concat all NTE-3",
            "schema_comment_2": "//OBX[@3.1='80398-1']-5 is a CX",
			"isolate": { 
				"id_number": "OBX[@3.1='80398-1']-5.1",
				"check_digit": "OBX[@3.1='80398-1']-5.2",
				"check_digit_scheme": "OBX[@3.1='80398-1']-5.3",
				"assigning_authority": {
					"namespace_id": "OBX[@3.1='80398-1']-5.4.1",
					"universal_id": "OBX[@3.1='80398-1']-5.4.2",
					"universal_id_type": "OBX[@3.1='80398-1']-5.4.3"
				},
				"identifier_type_code": "OBX[@3.1='80398-1']-5.5",
				"assigning_facility": {
					"namespace_id": "OBX[@3.1='80398-1']-5.6.1",
					"universal_id": "OBX[@3.1='80398-1']-5.6.2",
					"universal_id_type": "OBX[@3.1='80398-1']-5.6.3"
				},
				"effective_date": "OBX[@3.1='80398-1']-5.7",
				"assigning_agency": {
				            "id": "OBX[@3.1='80398-1']-5.8.1",
				            "text": "OBX[@3.1='80398-1']-5.8.2",
				            "code_system": "OBX[@3.1='80398-1']-5.8.3"
				}
			},
            "specimen": {
				"id": "SPM-2",
				"placer_assigned_id": "SPM-2.1",
				"filler_assigned_id": "SPM-2.2",
				"type": "SPM-4",
				"source_site": "SPM-8",
				"role": "SPM-11",
				"collection_amount": "SPM-12",
				"description": "SPM-14",
				"collection_datetime": "SPM-17",
				"received_datetime": "SPM-18"
			}
        }
		]
	}
]
}
```

**Comment by mscaldas2012** [comment]
We did implement the Parent/Child relationship on DAART - so, if this is something useful we can include it here as well...

**Comment by lmcnabb** [comment]
@mscaldas2012 can you put an estimate on this one?
