### ISSUE TITLE
Databricks: Create MMG-based model

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#324]
Feasibility/Design of SQL model from MMG-based model

**Comment by raman-cdc** [comment]
- Create raw SQL table for MMG Model from the Eventhub streaming Delta table
- Create processed/refined (Bronze/Silver) SQL table/view with flattened structure for MMG Model 
- Specify Data types for above tables attributes if required.
-  Validate with business 
-

**Comment by raman-cdc** [comment]
Created tables to stream data from Eventhub for Message processor Ok and Message Processor Err
