### ISSUE TITLE
Rename Function "Message Processor" to "MMG-Based-Transformer"

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#328]
More likely, we will end up with multiple Transformations / Message Processors!
Therefore we need to better specify our current message processor as being the MMG-Based Message Processor.

Suggestion: **MMG-Based-Transformer** or MMG-Based-Message-Processor (although I like Transformer better, since the entire pipeline is a message processor. This specific step is about transforming the message)

- [ ] Update Function name
- [ ] Update folders/project names
- [ ] update MpProcessMetadata

**Comment by rmharrison** [comment]
FFR...
In Nov 2022, our architecture assumed a single "Message Processor" to transform HL7v2 content into a format suitable for consumption by our CDC program consumer.

In Dec 2022, we opted to seperate the functionality of the "Message Processor" into separate transformer services.
- MMG-based (completed as of 2022-12-16)
- MMG-in-SQL (in progress as of 2022-12-16)
- Lake of Segments (not started as of 2022-12-16)

See also, #319
