### ISSUE TITLE
DataBricks - Incoming Stream - To SQL Models (Parquet)

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/data-exchange-hl7#33]
Topic availability

- [x] Set-up DBx
- [x] Receives Event Hub streams
- [x] Transforms MMG Model (Map - JSON) to SQL (Parquet) - Model A - one row per case notification ( streaming notebook )
- [x] Transforms MMG Model (Map - JSON) to SQL (Parquet) - Model B - multi table  ( streaming notebook )
- [x] SQL Analytics endpoint available
- [x] Integration with EDAV

- [ ] *Potentially design (and develop) sequencing, last case, etc.. flags - code only - (not doing right now)
- [ ] *Potentially integrate with Grafana 
- [ ] **Potentially integrate SQL API ( TBD ) (not doing right now)

**Comment by mscaldas2012** [comment]
All *Potential* postponed.
