### ISSUE TITLE
Discovery and planning for obtaining raw data feeds from four known sources:  PHIN MS, SDX, SFTP, S3)

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#334]
We need to discover and document the technical work needed to move each of these four feeds into DEX's Azure Storage folder (at the front of the pipeline) in a production manner.  Each of these locations/entry points into CDC may require a different LOE.  Some LOE by us, some by NNDSS, to be defined.

1. PHIN MS

~2. SDX~

~3. SFTP~

4. AWS S3 bucket (where 9 states drop NNDSS messages for MVPS to pickup)

**Comment by rmharrison** [comment]
For 2023Q2 > HL7v2 > Case
In Scope: Raw HL7v2 messages
  * PHINMS
  * AWS S3 / SFTP

Out of Scope
- NETTS
- NBS Master Messages

On 2023-01-30, DEX + PHINMS + MVPS agreed on a technical path to get the PHINMS messages. #499
As of 2023-01-30, a path for the AWS S3 messages is pending. #500

**Comment by mscaldas2012** [comment]
Moving into Implementation phase.

**Comment by rmharrison** [comment]
FFR: Implementation phase issues...
- #499 (PHINMS)
- #500 (CDH AWS S3)

SDX and SFTP are NOT used for HL7v2.
So we aren't implementing these feeds yet.
