### ISSUE TITLE
Create new EventHubs due to Renaming by OPS team

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/data-exchange-hl7#343]
App
- #414

Ops
- Functions: #371
- EventHubs: #343

Priority 1: Done on 2 Dec
Everything else: Scheduled for Thu 15 Dec

To create 4 new Event Hub topics:
- hl7-lake-segments-ok
- hl7-lake-segments-err
- hl7-message-processor-ok ==>(Rename) hl7-mmg-based-ok
- hl7-message-processor-ok ==>(Rename) hl7-mmg-based-err
- hl7-mmg-sql-ok [Priority 1  - Done 2022-12-02]
- hl7-mmg-sql-err [Priority 1 - Done 2022-12-02]

**Comment by boris-ning-usds** [comment]
Aligning with https://fearless.jira.com/browse/CDC-88.

**Comment by boris-ning-usds** [comment]
Aligning with https://fearless.jira.com/browse/CDC-88.

**Comment by cosmycx** [comment]
Can you pls delete these topics now, whenever possible.  @boris-ning-usds Thanks!
![image](https://user-images.githubusercontent.com/11874351/205319977-c8c0eb8f-1574-4b11-890d-7732552f332c.png)

**Comment by boris-ning-usds** [comment]
Yep, on it.

**Comment by boris-ning-usds** [comment]
@cosmycx 
When I delete these two Eventhubs, the function app - fn_message_processor_function_app is yelling at the dependencies on these two Eventhubs - for app settings EventHubSendErrsName and EventHubSendOkName which points to these Eventhubs.

I talked to @raman-cdc and he said @dtx0111 and he was working out of these two Eventhubs.

I'm halting this effort of deleting these two Eventhubs until it's cleared up.
