### ISSUE TITLE
update MMG-Based Transformer to use getMMG from lib-dex 1.0.3

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#357]
The new getMMGs() method on lib-dex-commons 1.0.3 throws an error if the condition code cannot be found.
Code using that method needs to appropriately catch the InvalidConditionException and send messages to error Topics.

**Comment by cosmycx** [comment]
This already works for getMMG that would throw an error
![image](https://user-images.githubusercontent.com/11874351/205741699-bbe4b50c-6e3e-4018-827e-47f6212acd2a.png)
