### ISSUE TITLE
Create AZ Function for necessary transformations from MMG-Based model into MMG-SQL model

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#369]
In order to dynamically create a MMG-In-SQL model from the MMG-Based model schema, we still need to read mmg configuration and HL7 data type fields configurations.

The function will still generate a single JSON with all the transformations. DBX will then split the Json into multiple tables/Data frames linked by message_uuid.

**Comment by cosmycx** [comment]
-[x] single blocks single elements
-[x] single blocks repeated elements
-[ ] repeated blocks with elements
-[ ] consume from MMG-based
-[ ] send to MMG-SQL topics
-[ ] Databricks
