### ISSUE TITLE
Create new Functions due to Renaming by OPS team

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#371]
App
- #414

Ops
- Functions: #371
- EventHubs: #343

Priority 1: Done 6 Dec 2022
Everything else: Scheduled for Thu 15 Dec

Create brand new functions due to renaming:

- [x] ocio-ede-dev-hl7-mmg-based-transformer (*)
- [x] ocio-ede-dev-hl7-cache-loader
     - [x] extra config:
          - [x] MMG_AT_TIME_TRIGGER = "0 0 7 * * *"
          - [x] PHINVOCAB_TME_TRIGGER = "0 0 9 * * * "
- [x] ocio-ede-dev-hl7-receiver-debatcher (*)
     - [x] extra config:
          - [x] BlobIngestConnectionString
          - [x] BlobIngestContainerName
       
- [x] ocio-ede-dev-hl7-mmg-validator (*)
- [x] ocio-ede-dev-hl7-structure-validator (*)
- [x] ocio-ede-dev-hl7-mmg-sql-transformer (*) [Priority 1 - Done 2022-12-06]
- [x] ocio-ede-dev-hl7-lake-segments-transformer (*) [ RENAMED from ocio-ede-dev-hl7-lake-**of**-segments-transformer]

For the fn with asterisk above, make sure two Event Hub topics exists:
- [x] {prefix}-{fn-name}-ok (ex.: ocio-ede-dev-hl7-mmg-based-transformer-ok) [Priority 1 - Done 2022-12-06]
- [x] {prefix}-{fn-name}-err (ex.: ocio-ede-dev-hl7-mmg-based-transformer-err) [Priority 1 - Done 2022-12-06]

Configuration.
Each of the functions above should have the following configurations:

* EventHubConnectionString = {event hub namespace connection string}
* EventHubConsumerGroup = {fn-name}-cg-001
* EventHubReceiveName = {the previous OK event hub on the pipeline}
* EventHubSendOkName = {prefix}-{fn-name}-ok 
* EventHubSendErrName = {prefix}-{fn-name}-err 
* REDIS_CACHE_KEY = {az redis cache key}
* REDIS_CACHE_NAME = {az redis cache name}
* FUNCTIONS_EXTENSION_VERSION = ~4
* FUNCTION_WORKER_RUNTIME = java
* WEBSITE_RUN_FROM_PACKAGE = 1

 Ops specific keys:

* APPINSIGHTS_INSTRUMENTATIONKEY
* APPLICATIONINSIGHTS_CONNECTION_STRING
* AzureWebJobsDashboard
* AzireWebJobsStorage

**Comment by boris-ning-usds** [comment]
Hmm, topic of conversation, I want to talk about the consumer group setup: 
Is the tag `cg-001` supposed to represent something?

These are the list of items I'm looking at for this ticket:

Function App naming consistency:
Use the naming convention: ocio-ede-dev-hl7-mmg-based-transformer

Tasks:
1. Remove all fn- in function app name, it's pretty explicit that these are function apps.
1. fn-message-processor changed to mmg-based-transformer
1. mmg-vocab changed to cache-loader
1. remove message_processor eventhubs (ok and error eventhubs). Replace with mmg_based_transformer eventhub.
1. Two new function app: mmg-sql-transformer and lake-of-segments-transformer
1. One new consumer groups: mmg-based-ok

External Task:
1. Create a table of new private endpoints FQDN to IP address naming since function app naming has changed.
1. Coordinate with CDC DNS team to setup DNS entries.
1. Decommission old DNS entries.

**Comment by boris-ning-usds** [comment]
Looking at it, I also like *ocio-ede-dev-hl7-* better than *ocio-ede-dev-hl7-*, any votes on that?

**Comment by mscaldas2012** [comment]
I assume you're comparing ocio-ede-dev-hl7 to ocio-ede-hl7-dev ... I personally don't like because I'd like to follow the format 
<OPS-prefix>-<ENV>-<Proj>-<name> where ops-prefix and env is controlled by the ops team... proj, can be hl7 or csv for example

say  you have 
ocio-ede-dev-hl7-xyz, ocio-ede-prd-hl7-xyz
ocio-ede-dev-csv-xyz

better than ocio-ede-hl7-dev-xyz, oico-ede-csv-dev-xyz... looks like we're mixing stuff

**Comment by boris-ning-usds** [comment]
Got it. I'll do that naming convention.

I'm going to take this ticket as a piecemeal, and try to make additive changes, and for every removal/update type change - such as name change from mmg-vocab -> cache-loader, it'll be coordinated with the developers.

**Comment by boris-ning-usds** [comment]
I've completed all the initial tasks marked as a priority, including the coordination with the DNS setup.

Marking it as **waiting** because the remaining tasks has to do with renaming, and it's better to sit down together to coordinate those changes.

**Comment by boris-ning-usds** [comment]
I've completed all the initial tasks marked as a priority, including the coordination with the DNS setup.

Marking it as **waiting** because the remaining tasks has to do with renaming, and it's better to sit down together to coordinate those changes.

**Comment by boris-ning-usds** [comment]
This has been completed.

I synced up with Neelima for these changes, and she's got cache-loader adopted into her code.
The other functions will need some level of follow up with Cosmin.

**Comment by boris-ning-usds** [comment]
This has been completed.

I synced up with Neelima for these changes, and she's got cache-loader adopted into her code.
The other functions will need some level of follow up with Cosmin.
