### ISSUE TITLE
Azure Eventhub to DBx Table Mappings

### ISSUE THREAD

**Issue by raman-cdc** [CDCgov/data-exchange-hl7#380]
Below is a Matrix for Eventhubs to Table mappings.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/RJ/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/RJ/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Event   Hubs | Delta Tables Per Eventhub | MMG-In-SQL Model Tables     Bronze
-- | -- | --
hl7-file-dropped | tbl_hl7_file_dropped |  
hl7-mmg-validation-err | tbl_hl7_mmg_validation_err | tbl_hl7_mmg_err_bronze
hl7-mmg-validation-ok | tbl_hl7_mmg_validation_ok | tbl_hl7_mmg_ok_brone
hl7-recdeb-err | tbl_hl7_recdeb_err |  
hl7-recdeb-ok | tbl_hl7_recdeb_ok |  
hl7-structure-err | tbl_hl7_structure_err | tbl_hl7_structure_err_bronze
hl7-structure-ok | tbl_hl7_structure_ok | tbl_hl7_structure_err_bronze
  |   |  
hl7-mmg-based-err | tbl_hl7_mmg_based_err | eh_hl7_mmg_based_err_bronze
hl7-mmg-based-ok | tbl_hl7_mmg_based_ok | eh_hl7_mmg_based_ok_bronze
  |   |  
hl7-mmg-sql-err | tbl_hl7_mmg_sql_err |  
hl7-mmg-sql-ok | tbl_hl7_mmg_sql_ok |  
  |   |  
hl7-lake-segments-err | tbl_hl7_lake_segments_err |  
hl7-lake-segments-ok | tbl_hl7_lake_segments_ok |  
  |   |  
hl7-quarantine | TBD |  
  |   |  
hl7-message-processor-err | tbl_hl7_message_processor_err | To be Deleted
hl7-message-processor-ok | tbl_hl7_message_processor_ok | To be Deleted

</body>

</html>

**Comment by lmcnabb** [comment]
@raman-cdc Can you put an estimate on this one?

**Comment by raman-cdc** [comment]
It. is complete for now and will keep updating it as there are changes in Event hubs or Raw streaming tables

**Comment by raman-cdc** [comment]
Updated Eventhub to Delta Table Mapping

<img width="467" alt="Screenshot 2022-12-29 at 7 36 03 PM" src="https://user-images.githubusercontent.com/97614308/209964632-05d39f64-2c57-45a5-ab72-009ed7469189.png">
