### ISSUE TITLE
Discover and design additional validation for the lab template, after structural validation

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#387]
While we initially didn't forecast having to do validation on the lab template after the structural validation step (NIST IGAMT validator), after reviewing Hepatitis messages containing the lab template and associated error/warning messages, it is clear that we need to do more exploratory work on the validation being done on the lab template.  We should aim to be on-par with possible with current, and if not, then we need to uncover the reasons and document.

Definition of done:
Conduct deep dive between product and developers
Document here a list of what validation we _are_ going to do.
Create another issue for the work to describe how we will implement.

*Note:  linking this to MMG validator epic as any work done would likely fall under that

**Comment by mscaldas2012** [comment]
Slides 10 to 16 talks about Lab template and some validation rules that are needed - Is this PPT up to date? can we base our validation rules on it?
[lap tempate presentation](https://cdc.sharepoint.com/:p:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/NMI-eSHARE-2018-05-508.pptx?d=w0adcc91c03b34095b1ed3afd4e98a406&csf=1&web=1&e=uw6ziS)

**Comment by lmcnabb** [comment]
Yes, assume it is correct for now and go off it until we can have convo in more detail with the team.

**Comment by mscaldas2012** [comment]
I believe we (@marcia-schulman :)) can create a MMG_AT->Like document for Lab Template only based on the validation rules on that PPT and the attached [Excel ](https://cdc.sharepoint.com/:x:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/Laboratory-Template_R1_20180511.xlsx?d=w8a303ed25e4d438db939fde211f27f4f&csf=1&web=1&e=rpln1Z)

MMG-Validator can be improved like this:
Lab template does not Apply to legacy or GenV1 messages. (Only GenV2 and condition specific)

* For EPI-OBR : validate all its OBXs against MSH_21 MMGs.
* All other OBRs are Lab OBRS: validate against the lab-template MMG created.

**Comment by lmcnabb** [comment]
@marcia-schulman @mscaldas2012 could you update this issue based on our discussion today?  Can you cross reference the ppt M attached with the tabs from the spreadsheet we looked at today as part of the work for this issue?  I'd like to have a master list of what we are going to implement.
