### ISSUE TITLE
Create appropriate consumer groups for all Event Hubs

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#389]
Currently, each Event Hub Topic is being consumed at least from three different consumers:
* The next function on the pipeline 
* Databricks
* Azure Data Explorer

Each of our event hubs need to have those three consumer groups terraformed.

Nomenclature suggestion:
* {function_name_consuming_the_topic}_cg_001
* dbx_{event_hub_name}_cg_001
* azdataexplorer_{event_hub_name}_cg_001

**Comment by boris-ning-usds** [comment]
(Checked with Marcelo): not every Eventhub is intended to have a consumer group for the next function, since some eventhub are there to hold errors.

**Comment by boris-ning-usds** [comment]
(Checked with Marcelo): Getting agreement on using "-cg-001" instead of "_" because function apps and eventhub are all using "-" for naming.
