### ISSUE TITLE
Deliver SQL table of test messages to customer 

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#405]
In the 2022-12-14 Sprint Review, the customer asked for a "view" of some kind (preferably SQL) of the test data that they have sent to us.  We should create a SQL table of Lyme/TBRD messages and a table of Hepatitis messages when the MMG-in-SQL work is closer to completion.  It will allow them to high level review the structure and actually compare what we have against their test messages.  They will be looking at error/warning information in reports as well, so we need to be on our game on that one.

Will email EDAV team to request Databricks AD group for the names provided to us by Lyme/Arbo/Hep programs.

**Comment by mscaldas2012** [comment]
We will provide the following tables:

- Structure Validation Report
- MMG Validaton Report
- MMG Based table
- **Strech** MMG-in-SQL Tables.

**Comment by mscaldas2012** [comment]
Will continue to work on MMG_in_SQL repeating tables next sprint
