### ISSUE TITLE
Implement Routing for Validation Reports

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#409]
We need to implement Consumption routing (by program) for the validation Reports.

These reports all have the same schema, so we have some options on how to implement this.

**Option 1 (Selected) - Provision separate tables for each program (based on message_info.route metadata -TBD) in the same way that we will implement for the actual HL7 Messages.**

Option 2 - Keep single table with all data and force filtering on the views by program...

**Comment by mscaldas2012** [comment]
we went with Option 1

**Comment by rmharrison** [comment]
@mscaldas2012 
> Option 1 (Selected) - Provision separate tables for each program (based on message_info.route metadata -TBD) in the same way that we will implement for the actual HL7 Messages.

Is HL7v2 > Databricks > Validation diagram up to date with this architecture decision?

I read the diagram as saying the bronze, silver and gold tables have messages for ALL programs (Option 2)
==> Where do you switch from table having all validation messages, to one table per program?
==> Update diagram accordingly?

![2023-01-25 DEX HL7v2 - Databricks - Validation Tables.png](https://images.zenhubusercontent.com/62fe6e4e7c59c94524ab80ae/9d222dbf-c6f0-40f3-ad36-ad13508b49b8)
Source: Lucid > DEX HL7v2 Azure Pipeline > tab: Databricks pipeline

**Comment by rmharrison** [comment]
Clarified on Sprint Review, 2023-01-25

1 table per program happens at GOLD
Bronze and Silver tables are NOT segmented by program

Updated diagram...
![2023-01-25 DEX HL7v2 - Databricks - Validation Tables v2.png](https://images.zenhubusercontent.com/62fe6e4e7c59c94524ab80ae/cee9e840-95cb-4a66-befc-4e7ece46fec0)

Source: Lucid > DEX HL7v2 Azure Pipeline > tab: Databricks pipeline
