### ISSUE TITLE
Refactor dbx notebook repo structure

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#415]
Add folder for each medallion-style notebooks for pipeline.

![image](https://user-images.githubusercontent.com/3239945/207910526-9927fb50-2f45-47b2-ae08-f08eb1ae71e9.png)

**Comment by raman-cdc** [comment]
Created pipeline folder structure and checked in code 

<img width="934" alt="Screenshot 2022-12-21 at 8 28 50 AM" src="https://user-images.githubusercontent.com/97614308/208955366-1afe3ed1-0e42-4f62-92c8-3de4de5cea93.png">
