### ISSUE TITLE
Determine why NIST Validator does not validate OBX-4, Observation Sub-ID

### ISSUE THREAD

**Issue by marcia-schulman** [CDCgov/data-exchange-hl7#420]
We have found that repeating OBX segments with the same OBX-3 value and the same (or missing) OBX-4 value are not flagged as errors by the IGAMT testing tool (GVT). OBX-4 is defined as conditionally required, with the condition being a repeated OBX-3 value.  The combination of OBX-3 and OBX-4 must be unique.

The rule is described in both the PHIN Spec (v.3 was referenced) and the HL7 base specification (v.2.5.1, Chapter 7).

**Comment by marcia-schulman** [comment]
The Conditional (R/RE) on OBX-4 that I thought had been configured as a rule in the IGAMT profiles is actually just free text (see attached image). I have posted a question on the IGAMT users google group site asking how to configure this rule for real. I have played around with the conditional rule builder trying to come up with a solution and suspect there is not a way to do it in IGAMT.
![image](https://user-images.githubusercontent.com/111081583/208499179-a7cb9744-1bcd-40f2-9676-6b8038f23306.png)

**Comment by marcia-schulman** [comment]
Received this reply, which confirms the OBX-4 check cannot be done via the NIST validator:

> From: Rosin, Caroline D. (Assoc) <[caroline.rosin@nist.gov](mailto:caroline.rosin@nist.gov)>
Date: Tue, Dec 20, 2022, 3:03 PM
Subject: Re: How to validate OBX-4, Observation Sub-ID
To: Marcia Schulman <[mcupery@gmail.com](mailto:mcupery@gmail.com)>, NIST-IGAMT <[nist-igamt@googlegroups.com](mailto:nist-igamt@googlegroups.com)>

> Hello Marcia,
there is no easy way at the moment to add that kind of check in IGAMT.
We could try to work on a hybrid solution, but I would need more details. The solution we can propose is that NIST would write some custom plugin and add it to NIST GVT.
If you are using another platform than GVT to validate messages let me know.

> The plugin would be specific to your message profile (most likely will not be reused anywhere else). In order to implement it, I need more information on what exactly constitute a valid or invalid combination of OBX-3/OBX-4 for your message profile.

> 1.	OBX-3 is complex, what are the components that we need to look at to compare values across the OBXs segments ?
> 2.	Is your OBX-4 a primitive datatype (ST) or complex (OG) ?
> 3.	Is the combination unique within the whole message or a particular group ?

> Thank you,
> Caroline Rosin

**Comment by lmcnabb** [comment]
@marcia-schulman so does this mean we need to create this validation in the MMG validator?  If so, can you link this issue to the issue where that work will be done?
