### ISSUE TITLE
Create a normalized delta table for structure-err event hub metadata.

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#431]
create a delta table for properties "metadata.provenance" & "summary".

Create hl7_structure_err_silver table with streaming.

**Comment by mscaldas2012** [comment]
Better ticket #436 created to handle this.

**Comment by mscaldas2012** [comment]
I don't see the table referenced here... moving this back to in Progress to chat with Neelima and see what needs to be done for this ticket.
