### ISSUE TITLE
Include errorCount and WarningCount columns on validation bronze tables. Create Silver Tables

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#436]
Right now the validation bronze tables have either a issuesAndErrorCoutn or just errCount.

Change all 4 tables to have errorCount and warningCount tables:
- [x] hl7_mmg_validation_err_bronze
- [x] hl7_mmg_validation_ok_bronze
- [x] hl7_structure_err_bronze
- [x] hl7_structure_ok_bronze

Then create Silver tables according to diagram:

![image](https://user-images.githubusercontent.com/3239945/208993784-9e3a8849-4a93-45de-aa09-b3bee8e5f223.png)

**Comment by raman-cdc** [comment]
Modified bronze tables to include 
errorCount
warningCount

<img width="997" alt="Screenshot 2022-12-29 at 7 03 09 PM" src="https://user-images.githubusercontent.com/97614308/209961067-66804503-584a-4fc6-90e3-736903ded269.png">

**Comment by mscaldas2012** [comment]
Silver tables still not created - will tackle that on new ticket
