### ISSUE TITLE
Split MMG-SQL table into multiple tables

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#452]
The MMG-in-SQL Table comes as a single JSON to DBX bronze tables.
These need to be separated into its own tables.

All repeat elements are under a "tables attribute on the main schema. Each repeat should become its own table (after routing to proper program/route).

Ex.;
![image](https://user-images.githubusercontent.com/3239945/210793823-00e7bede-7865-434f-9048-36ad584b44dd.png)

Preferably we can do this dynamically by splitting any child of tables into its own table.

- [x] Bronze Notebook: Raw -> Bronze data
- [x] Silver Notebook: Bronze -> Silver data
- [x] Gold Notebook: Silver -> Gold data, to include Routing
---
- [x] Line up schema Bronze
- [x] Line up schema Silver
- [x] Line up schema Gold
---
- [x] Gold refactor to streaming: change to batch process per mmg and to foreachbatch
---
- [x] Bronze switch to streaming (possible anytime)
- [x] Silver switch to streaming (possible anytime)
- [x]  Gold switch to streaming (blocked by gold refactor to streaming above)

**Comment by cosmycx** [comment]
https://github.com/CDCgov/data-exchange-hl7-dbx/pull/21
https://github.com/CDCgov/data-exchange-hl7-dbx/pull/24
