### ISSUE TITLE
Create Static table for Routes in DBX

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#482]
Develop a notebook that populates a static table with all possible Routes to be used by other notebooks that needs to separate data by routes.

The notebook, ideally can read data from redis **condition:** table and refresh the table automatically - so that every time we onboard new Programs/routes, we can automate DBX to refresh it's static table.

**Comment by raman-cdc** [comment]
Currently we have static table which has route defined to separate the data.

**Comment by raman-cdc** [comment]
The routes are not available in Redis cache, so we could not populate the routes in table.
As an intermediate solution we

1. Created a static table to capture routes from eventhub  to be used across multiple notebooks.

**Comment by mscaldas2012** [comment]
A solution was found to dynamically query the routes coming from new messages and using those to create new tables. A static table is no longer needed.
