### ISSUE TITLE
Match Validation Tables to the schema below

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#484]
schema_validation_bronze = StructType([
     StructField("message_uuid", StringType(), True),
     StructField("metadata_version", StringType(), True),
     StructField("message_info", schema_message_info, True),
     StructField("summary", schema_summary, True),
     StructField("provenance",   schema_metadata_provenance, True),
     StructField("processes",    schema_processes, True),
     StructField("process_name", StringType(), True),
     StructField("process_version", StringType(), True),
     StructField("start_processing_time", StringType(), True),
     StructField("end_processing_time", StringType(), True),
     StructField("report", StringType(), True),  
  -- Validation Specific (all the above is common to all bronze tables)
     StructField("error_count", IntegerType(), True),
     StructField("warning_count", IntegerType(), True),
     StructField("validation_status", StringType(), True)
])

schema_validation_silver = StructType([
    StructField("message_uuid", StringType(), True),
    StructField("metadata_version", StringType(), True),
    StructField("message_info", schema_message_info, True),
    StructField("summary", schema_summary, True),
    StructField("provenance", schema_metadata_provenance, True),
    StructField("category", StringType(), True),
    StructField("line", IntegerType(), True),
    StructField("column", IntegerType(), True),
    StructField("field", StringType(), True),
    StructField("description", StringType(), True)
])

schema_validation_gold = same as silver, with filtered data by route.

**Comment by dtx0111** [comment]
Applied schema updates on hl7-structure-err & hl7-structure-err_ok until gold tables.
