### ISSUE TITLE
Build in support for all conditions (MMGs)

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#501]
Build in all MMGs into HL7v2 pipeline.  Prioritize NCIRD conditions and PHLIP flu messages into HL7v2 pipeline.  

![26f28cb3-ec4d-4a04-8f1f-9466c2bf6b2b.jpg](https://images.zenhubusercontent.com/6230a6db53509272f2ac9e4b/fe27414a-6bc3-410a-9c65-00e08173cad3)

**Comment by rmharrison** [comment]
NB on Definition of Done
Marcia will create in MMGAT
And then reassign to QA to test in pipeline
