### ISSUE TITLE
Create a redaction function (generic) that can be used across all incoming HL7v2 data streams

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#508]
Need to develop a Function to redact HL7 messages.

* [x]  Request Ops team to create/Terraform a new function -> ocio-ede-dev-hl7-redactor
* [x]  Request Ops Team to create/Terraform new Event Hubs (with appropriate consumergroups)->
       - hl7-redactor-ok
       - hl7-redactor-err 
* [x]  Develop Function, create CASE config file (#111, #216)
* [x]  Re wire Pipeline to redact after Receiver-debatcher, before Structure (change the reading queue of Structure validator to read from hl7-redactor-ok (needs terraform changes)
* [ ] Create Notebook to generate raw and bronze tables of the two event hubs above.

**Comment by mscaldas2012** [comment]
Will create DBX tables next Sprint.
