### ISSUE TITLE
Terraform Dev AZ Redis tempedehl7

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#52]
Need to terraform AZ Redis. Created one manually for immediate development that can be deleted once we have terraform scripts -> current Resource: tempedehl7.

Suggested Configuration:
- [X] DEV -> Name: edehl7dev; Type: Basic C0 (250Mb, no replication) ($16/month)
- TST ->  Name: edehl7tst; Type: Standard C1 (1Gb + Replication) ($100/month)
- STG -> Name: edehl7stg; Type: Standard C1
- PRD -> Name: edehl7; Type: Standard C1 (if we want Redis persistence, it will require Premium layer - P1 $202.21/month with options of reserved instances.)

**Comment by mscaldas2012** [comment]
Once Terraform is created and run against DEV, create a ticket so developers can switch configuration to the new Redis service.

**Comment by boris-ning-usds** [comment]
Created #148 for tracking all the other environments. Moving to completed.
