### ISSUE TITLE
Create HTTP endpoints for all 3 MRR functions

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#526]
- [ ] Refactor MRR code so business logic can be used in multiple functions
- [ ] Create HTTP Endpoint to load each of the 3 sets of data into Redis.
  - Event Codes
  - Phin Vads
  - MMGs

**Comment by cosmycx** [comment]
Azure Cache Redis is moving to premium - Probably no longer needed.

**Comment by mscaldas2012** [comment]
Also we found a workaround where we can execute functions with a azure endpoint provided for each function via <FN_URL>/admin/functions/<function name>

Examples on the Postman collection on teams.

**Comment by rmharrison** [comment]
Stale issue.

MMG Validation was removed from DEX HL7v2 Validation pipeline on 9 Aug 2023 in [v0.0.25](https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.25/CHANGELOG.md)

The Redis cache used to load...
- condition:
- mmg:
- vocab:

Was only used for MMG validation, and was therefore removed.
