### ISSUE TITLE
Enhance Receiver-Debatcher support lab messages

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#532]
The Receiver-debatcher will need to read AZ object metadata and provide that as part of message info and provenance metadata.
		
- message_type: enum['CASE', 'ELR'] -- currently we're supporting case or ELR
- route: The program these messages belong to…."COVID"
- reporting_jurisdiction: FIPS Code of State/Territory sending this message. (COVID uses free form here)
- ext_system_provider: The system that is providing the data to DEX (PHINMS, BulkUpload, Mercury, etc)
- ext_original_file_name: The original file name used by the sender to send this message.   
- ext_received_timestamp: Timestamp when CDC first received the message (on any system)
     
### Validation:
 (If required fields are not present, they should go to hl7-recdeb_err queue.)
- Message_type is required (Must be CASE or ELR?)
- route is required for ELR (program can be determined for CASE from HL7)
- Reporting_jurisdiction is required for ELR (rep_jur can be determined for CASE from HL7)
- Ext_system_provider is optional
- Ext_original_file_name is optional
- Ext_received_timestamp is optional

### **Mapping:**
message_type -> message_info.type
reporting_jursidiction ->message_info.reporting_jurisdiction
route -> message_info.route
ext_system_provider -> provenance.ext_system_provider
ext_orginial_file_name -> provenance.ext_original_file_name
ext_received_timestamp -> provenance.ext_original_file_timestamp (**NEW** needs to be created in lib-dex-commons)

Once the transport service uploads the file these metadata will be available:
![image](https://user-images.githubusercontent.com/3239945/224044873-5c376679-8a70-4def-b710-4fbab7ab29f6.png)

**Comment by mscaldas2012** [comment]
Routing can't have special characters other than underscore ("_")

**Comment by mscaldas2012** [comment]
case sensitive header names and values?
