### ISSUE TITLE
GENv2 HL7 Validations: Blanket Processing:  ReqID-00001 - Update needed for data elements with May Repeat = No

### ISSUE THREAD

**Issue by nadiackhan** [CDCgov/data-exchange-hl7#545]
**Reference document:** [NND Requirements ](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/NND%20Requirements%20Implementation%20Matrix%20-%202022-12-16%20DEX.xlsx?web=1)
**TAB:** Blanket Processing
**REQ ID:** 00001
**Validator** - Structure

**QA:** Data elements tested based on GenV2 with **CDC Priority** of **R** and **1**
Please review validations of **Data elements with “May Repeat” defined as “No”** 

**Expected Results:** - A Warning must be returned for data elements with “May Repeat” defined as “No”

See test results on tab **QA -Reqid 00001 May Repeat = No**  [here](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/QA%20Validation%20of%20Generic_V2_0_1_MMG-and-TS_F_20210722%20(1).xlsx?web=1)
**NOTE:**  Please filter by **Scenario Name/File Name** column

**Postman Collection** **DEX Genv2- Cardinality Validation ReqID 00001 & 00002.postman_collection** is [here](https://cdc.sharepoint.com/:f:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/Postman?csf=1&web=1&e=51su1z)
Linked to #510

**Comment by mscaldas2012** [comment]
Cardinality issues (May Repeat) are handled in our MMG validator on DEX pipeline.

**Comment by nadiackhan** [comment]
Retest this. The structure validator is still throwing an Error.

**Comment by nadiackhan** [comment]
Validated & Closed. The cardinality now throws a warning. Test documentation updated with new results.
