### ISSUE TITLE
Update MRR to use new lib-dex-commons library with dot normalization

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#547]
Update MRR with latest lib-dex-commons version to normalize dots and reload Redis Cache.

Identify issues with pipeline after this change and create tickets/fix bugs encountered.

**Comment by marcia-schulman** [comment]
This is done and we also changed all the namespaces back to the original names, which do not include version numbers, i.e. "condition:", "group:", "mmg:", and "vocab:"
