### ISSUE TITLE
Terraform Dev Az Storage Acct stedehl7ingressdev

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#55]
Need to terraform our Storage account where HL7 files can be dropped.
resources to terraform:
* storage Account
*  container
*  Event to publish "Blob Create to our EventHub. (issue #54)

Config:
[ ] All -> Perf.: Std., Redundancy ; Geo; Diable soft deletes.
   Need to identify network access - dev is public open right now, but higher env. can probably be limited to virtual clouds. Redundancy might be increased for PRD if deemed necessary - 
THIS IS NOT a Storage Account STLTs will have access to. 

- [x] DEV -> Name: tfstedehl7ingressdev
- TST -> Name: tfstedehl7ingresstst
- STG -> Name: tfstedehl7ingressstg
- PRD - > Name: tfstedehl7ingress

**Comment by mscaldas2012** [comment]
This ticket depends on #54 -> I'm not saying we need separate Terraform scripts, but found it better to create individual tickets for each set of resources we need.

**Comment by boris-ning-usds** [comment]
This is completed for the DEV environment for both the HL7 and CSV team.
The agreement is that they'll share one storage account and make containers for separating their dataset.

The private endpoint has been created, AD team has been asked to create DNS, and I have verified DNS completion.

Other environments (TEST, Staging, Prod) should be talked about at a different ticket.

**Comment by boris-ning-usds** [comment]
And "Events" above refer to Event Grid for blob creation.

**Comment by boris-ning-usds** [comment]
Added those two containers and setting up event subscription.
I picked different namings since the system topics were conflicting and I can't use the ones you are using.

Feel free to verify the messagestorage dev storage account.

**Comment by mscaldas2012** [comment]
Everything looks great!
We'll hook up the Receiver Debatcher to this next. (then we can delete the manual storage created -stedehl7ingressdev
