### ISSUE TITLE
GENv2 HL7 Validations: Blanket Processing: ReqID 00026 - Update the error message when OBR-4 is incorrect. Error is not coming from MMG Validator

### ISSUE THREAD

**Issue by nadiackhan** [CDCgov/data-exchange-hl7#555]
[NND Requirements](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/NND%20Requirements%20Implementation%20Matrix%20-%202022-12-16%20DEX.xlsx?web=1) - Req ID - 00026 under **Blanket Processing** tab
and 00054 under **MPG RULES - Validation**
[Value set for OBR-4](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.1107) 
[Postman collection](https://cdc.sharepoint.com/:f:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/Postman?csf=1&web=1&e=rNy6hv)  - **DEX Bugs.postman_collection**

1. Send a message with OBR-4 value that is **not** 68991-9^Epidemiologic Information^LN
2. Validate that the MMG Validator returns the following error: 
Error Message: **An unsupported literal value was provided for the Universal Service Identifier (OBR-4). Replace the unsupported literal value with the required literal value as defined within the current version of the appropriate MMG.**

**Actual Result:** **Structure Validator** throws the following error: 
![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/c547e6cb-555c-4a7c-85fb-61a06b0fc24e)
 **MMG Validator** does not throw any error message. 
**Expected Result:** MMG Validator should throw an error. 

![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/40ed2537-f824-41d0-90ce-eb1879655842)

![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/3deca207-2ba5-472c-852a-a9a8bcea7538)

**Comment by mscaldas2012** [comment]
@manandappa 
Remember, the Stack trace is not given to the user. The only message provided to the user is this:
![image](https://user-images.githubusercontent.com/3239945/226644432-f7f7c01c-2783-48fc-afc7-d6a9cd78021a.png)

Wondering why are you expecting to have the error thrown by MMG validator?

**Comment by nadiackhan** [comment]
{
    "entries": {
        "structure": [
            {
                "line": 6,
                "column": 139,
                "path": "OBX[3]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 10,
                "column": 111,
                "path": "OBX[7]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.406'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 14,
                "column": 118,
                "path": "OBX[11]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 22,
                "column": 110,
                "path": "OBX[19]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 24,
                "column": 116,
                "path": "OBX[21]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 26,
                "column": 129,
                "path": "OBX[23]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.114222.4.5.274'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 27,
                "column": 122,
                "path": "OBX[24]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 32,
                "column": 99,
                "path": "OBX[29]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 37,
                "column": 210,
                "path": "OBX[34]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 39,
                "column": 172,
                "path": "OBX[36]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.114222.4.5.274'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 40,
                "column": 157,
                "path": "OBX[37]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.114222.4.5.274'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 40,
                "column": 218,
                "path": "OBX[37]-5[2].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.114222.4.5.274'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 41,
                "column": 97,
                "path": "OBX[38]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 42,
                "column": 108,
                "path": "OBX[39]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 43,
                "column": 141,
                "path": "OBX[40]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 44,
                "column": 195,
                "path": "OBX[41]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 45,
                "column": 121,
                "path": "OBX[42]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 46,
                "column": 148,
                "path": "OBX[43]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 47,
                "column": 137,
                "path": "OBX[44]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 48,
                "column": 95,
                "path": "OBX[45]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 49,
                "column": 106,
                "path": "OBX[46]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 50,
                "column": 110,
                "path": "OBX[47]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 53,
                "column": 137,
                "path": "OBX[50]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 54,
                "column": 131,
                "path": "OBX[51]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 55,
                "column": 164,
                "path": "OBX[52]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 56,
                "column": 203,
                "path": "OBX[53]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 57,
                "column": 151,
                "path": "OBX[54]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 58,
                "column": 167,
                "path": "OBX[55]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 59,
                "column": 160,
                "path": "OBX[56]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 60,
                "column": 148,
                "path": "OBX[57]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 66,
                "column": 108,
                "path": "OBX[63]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 67,
                "column": 217,
                "path": "OBX[64]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 68,
                "column": 112,
                "path": "OBX[65]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 69,
                "column": 108,
                "path": "OBX[66]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 70,
                "column": 120,
                "path": "OBX[67]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 71,
                "column": 113,
                "path": "OBX[68]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 72,
                "column": 109,
                "path": "OBX[69]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 73,
                "column": 95,
                "path": "OBX[70]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 74,
                "column": 95,
                "path": "OBX[71]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 75,
                "column": 113,
                "path": "OBX[72]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 76,
                "column": 99,
                "path": "OBX[73]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.96'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 77,
                "column": 100,
                "path": "OBX[74]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 78,
                "column": 100,
                "path": "OBX[75]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.5.1008'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 79,
                "column": 96,
                "path": "OBX[76]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.92'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 80,
                "column": 106,
                "path": "OBX[77]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.93'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 81,
                "column": 128,
                "path": "OBX[78]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.92'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 82,
                "column": 137,
                "path": "OBX[79]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 83,
                "column": 144,
                "path": "OBX[80]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.114222.4.5.274'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 84,
                "column": 196,
                "path": "OBX[81]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 85,
                "column": 202,
                "path": "OBX[82]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 86,
                "column": 143,
                "path": "OBX[83]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 89,
                "column": 137,
                "path": "OBX[86]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.12.136'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            },
            {
                "line": 91,
                "column": 122,
                "path": "OBX[88]-5[1].3",
                "description": "The length of Component OBX-5.3 (Name of Coding System) must be within the range [1, 20]. Value = '2.16.840.1.113883.6.92'",
                "category": "Length",
                "classification": "Warning",
                "stackTrace": null,
                "metaData": null
            }
        ],
        "content": [
            {
                "line": 3,
                "column": 58,
                "path": "OBR[1]-4[1].1",
                "description": "CN-014-1 - If  OBR-1 (Set ID - OBR)  contain the value '1'.  then  OBR-4.1 (Identifier) shall contain the value '68991-9'. ",
                "category": "Constraint Failure",
                "classification": "Error",
                "stackTrace": [
                    {
                        "assertion": "OBR.1[1] SHALL not be equal to '1'  OR OBR.4[1].1[1] SHALL be equal to '68991-9' ",
                        "reasons": []
                    },
                    {
                        "assertion": "OBR.1[1] SHALL not be equal to '1' ",
                        "reasons": [
                            "[3, 1] The inner expression is true"
                        ]
                    },
                    {
                        "assertion": "OBR.4[1].1[1] SHALL be equal to '68991-9' ",
                        "reasons": [
                            "[3, 58] '55752-0' is different from '68991-9' (case sensitive)"
                        ]
                    }
                ],
                "metaData": {}
            }
        ],
        "value-set": []
    },
    "error-count": {
        "structure": 0,
        "value-set": 0,
        "content": 1
    },
    "warning-count": {
        "structure": 53,
        "value-set": 0,
        "content": 0
    },
    "status": "CONTENT_ERRORS"
}

**Comment by nadiackhan** [comment]
Closing this bug.  The current error coming from the structure validator is acceptable. 

![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/3aeb9f26-ef68-4185-b1b9-50056c1d3639)
