### ISSUE TITLE
Test the HL7 case *and* lab redaction configs

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#568]
QA Results can be found [here](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/QA%20Redaction%20Test%20Scenarios%20and%20Result.xlsx?web=1)

**Comment by nadiackhan** [comment]
Reviewed results with Marion.
