### ISSUE TITLE
Checksum mechanism on cache; Ability to check Redis cache is up to date as loaded with latest updated data.

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/data-exchange-hl7#571]
- Ability to check Redis is up to date in sync with the latest update performed for: MMG, Vocab, Condition Codes, etc....
- Ideally load the respective info, MMG, Vocab, etc.., from source controlled, visible sources. 
- Ability to simply check and confirm what is in Redis an any point.
- Ideally MRR - does not perform Redis update if is not needed such as there is no new info.

@mscaldas2012 , I think to have some form of checks to make sure the meta data is accurate is important. I think it's worth the effort to explore this in the next sprint.

--- Adding notes from Boris for reference
I'm concerned about the input to Redis as a caching strategy without some form of 
intermediate form to be able to do quick sanity check without directly going into 
the database.Redis just holds our key value pairs, and they're all just text at the end of the day.
 When running a periodic cron job every so often to load the data, 
I want the operation to be as simple as possible.
The outcome should be "Did the data load, or did it not load?"
1. If the cron job we ran succeeds in loading the data, success;
 and it should match up with an intermediate storage that's viewable in Github.
 After all, the key value pairs are all text, we can store them as text in Github with the ability to diff versions coming back 
from MMG API and PHIN Vocab.
2. If the cron job fails to load the data from the intermediate form from say... Github,
 then operations should step in to figure out why it didn't load. But the transparency 
should be provided by Github version + ensuring the Azure function ran.
My hope for outcome is:Cron job runs --> Github as intermediate cache.
Cron job runs --> pulls from Github for key value pairs --> pushes to Redis.
Instead ofCron job runs and pushes to Redis; with little transparency on what was done at all.

**Comment by mscaldas2012** [comment]
the whole point of loading data from PHINVADS and MMG-AT is to dynamically have latest changes available to use on pipeline - specially PhinVADS.
Loading that data from source controlled, visible sources Defeats the purpose in my opinion.

**Comment by mscaldas2012** [comment]
We have a Premium version with fault tolerance and it uses persistence of its data that gets reloaded when Redis comes back online.
Therefore this is no longer needed.

**Comment by rmharrison** [comment]
Stale issue.

MMG Validation was removed from DEX HL7v2 Validation pipeline on 9 Aug 2023 in [v0.0.25](https://github.com/CDCgov/data-exchange-hl7/blob/v0.0.25/CHANGELOG.md)

The Redis cache used to load...
- condition:
- mmg:
- vocab:

Was only used for MMG validation, and was therefore removed.
