### ISSUE TITLE
Evaluate Conformance Profiles for ELR

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#578]
When working/configuring the conformance profiles from CELR, we need to confirm that the COVID ELR NIST Conformance profiles are just a relaxed version of the ELR spec. and there is nothing specific to COVID, outside of the fact that a test was run and providing a positive/negative/inconclusive test result.

**Comment by mscaldas2012** [comment]
Scott Rank Provided answers - COVID profiles are a relaxed version of ELR profile and there's no COVID specific rules in them.
