### ISSUE TITLE
SPIKE: research Azure Blob Storage with SFTP

### ISSUE THREAD

**Issue by boris-ning-usds** [CDCgov/data-exchange-hl7#58]

**Comment by boris-ning-usds** [comment]
This is a SPIKE ticket for usage of Azure Blob Storage with SFTP for customers to send data to Data Exchange via SFTP.

@rmharrison and I have spoken at some legnths on the caveats and drawbacks of a solution like this and I will produce a documentation highlighting an approach we can take for customers to send data to us via SFTP.

This document should highlight how to operate / setup this environment, the networking involved in it, the compliance hurdles that we may incur, our ability to govern it, and other operational hurdles we may have.

**Comment by rmharrison** [comment]
Ryan lightly edited document and sent as read-ahead to CDC internal stakeholder.

**Comment by rmharrison** [comment]
2022-09-02: Ryan shared readahead with business team
