### ISSUE TITLE
Structure Validation Test Databricks tables to make sure errors and warnings are populated as expected 

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#587]
1. Drop messages with structural errors and test to make sure all appropriate messages are populated in the hl7_structure validation table
2. Drop messages with warnings and test to make sure all appropriate messages are populated in the hl7_structure validation table

**Comment by manandappa** [comment]
@nadiackhan can you please estimate?

**Comment by nadiackhan** [comment]
Validated the structure table: .ocio_dex_tst.hl7_structure_silver
Validated that the warnings and errors are correctly populated with the correct count.
