### ISSUE TITLE
Admin: File ticket for Marcelo to figure out why he couldn't spin up Azure functions

### ISSUE THREAD

**Issue by boris-ning-usds** [CDCgov/data-exchange-hl7#59]
Administrative ticket: I've talked to Stuart from the Cloud team regarding failures to spin up Azure functions, he said to file a ticket and he'll have somebody looking into it.

I need to file a Cloud Service Request ticket to follow up.

**Comment by mscaldas2012** [comment]
Just FYI, I was able to create a function App and a function inside it. What's failing is calling a "Deploy" from my local to push code to that azure function. it might be I have stuff misconfigured, but from the error I'm seeing , I'm getting a 401

**Comment by boris-ning-usds** [comment]
This has been completed - it looks like we ran into a permission problem due to selecting the wrong resource group.
