### ISSUE TITLE
MMG Based Model, fn-mmg-based-transformer -> filter lines to only consider OBX's under the EPI OBR for the model

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/data-exchange-hl7#617]
- This (getMessageLines) could be changed to only return the OBX's under the EPI OBR to avoid any weird edge cases, such an obx line with an obx identifier from the MMG could be under a non EPI OBR. 
(https://github.com/CDCgov/data-exchange-hl7/blob/develop/fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Transformer.kt#L256)

- Additionally the function (getMessageLines) should still return the MSH, PID, EPI OBR (the segment lines that are in MMG)

- Note: only the EPI OBR is used for the model: ref: https://github.com/CDCgov/data-exchange-hl7/blob/develop/fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Transformer.kt#L108

**Comment by marcia-schulman** [comment]
Not sure this is relevant. EPI OBX identifiers would not appear in lab elements, and Genv1/Legacy MMGs do not have an EPI OBR.

**Comment by marcia-schulman** [comment]
We will in fact need to filter out any OBRs that are lab-related, as these will have codes in OBR-31 that are not necessarily the same as the condition code for the MMG.
So a possible solution is to only examine OBRs with one of these 3 values in OBR-4.1:
68991-9
PERSUBJ
NOTF

It may be that 68991-9 and NOTF are sufficient.  NOTF indicates the OBR that comes right before the case OBXs in Genv1.

**Comment by marcia-schulman** [comment]
Will also need to account for this in MMG-Validator!
