### ISSUE TITLE
fn-mmg-based-model, add logic such as: Log Severe or Throw error if EPI OBR is not in the message

### ISSUE THREAD

**Issue by cosmycx** [CDCgov/data-exchange-hl7#618]
![image.png](https://images.zenhubusercontent.com/62e7bfa92e5c75a252672dc3/e976ad05-1817-4e7e-800a-6f65672379e1)

https://github.com/CDCgov/data-exchange-hl7/blob/develop/fns-hl7-pipeline/fn-mmg-based-transformer/src/main/kotlin/gov/cdc/dex/hl7/Transformer.kt#L108

**Comment by marcia-schulman** [comment]
This is unnecessary because the message would not pass structural validation without this segment.
