### ISSUE TITLE
Modify Lake of Segments FN to consume from multiple Event Hubs

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#619]
Lake of Segments have to consume both Case messages form hl7_mmg-valid-ok event hub and ELR messages from hl7-structure-elr-ok event hub

![image](https://user-images.githubusercontent.com/3239945/231238145-12caa64e-afb8-402c-9b5f-0de1b04debf3.png)

**Comment by mscaldas2012** [comment]
Actually, we could make Lake of segments consume directly from hl7-structure-ok messages - so that any message that passes structure validation will have a Lake of Segments model defined for it.

The caveat is that even messages that fail mmg-validation will also have a Lake of Segments.!

**Comment by guntukuhari** [comment]
MR - https://github.com/CDCgov/data-exchange-hl7/pull/828

**Comment by guntukuhari** [comment]
PR - https://github.com/CDCgov/data-exchange-hl7/pull/831

**Comment by guntukuhari** [comment]
PR is linked
