### ISSUE TITLE
Provide Access to MMG in SQL model  by creating an AD group to NCIRD

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#628]
Please provide MMG and SQL Model access to

 Sang (hyr5@cdc.gov),
John (rxq8@cdc.gov), 
Kiran (kka1@cdc.gov), 
and
 Shu (aky1@cdc.gov).

**Comment by raman-cdc** [comment]
Databricks AD groups 

gp-u-EDAV-DEX-NCIRD-DBR-ANALYST
gp-u-EDAV-DEX-NCIRD-DBR-DEVELOPER

**Comment by lmcnabb** [comment]
@raman-cdc or @ucf4 put an estimate on this one for me
