### ISSUE TITLE
GENv2 HL7 Validations: Blanket Processing: ReqID-00012 - Error message update needed for required OBX fields. 

### ISSUE THREAD

**Issue by nadiackhan** [CDCgov/data-exchange-hl7#629]
Reference document: [NND Requirements](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/NND%20Requirements%20Implementation%20Matrix%20-%202022-12-16%20DEX.xlsx?web=1)
TAB: **Blanket Processing**
REQ ID: **00012**
**See QA TEST RESULTS** [here](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/QA%20Validation%20of%20Generic_V2_0_1_MMG-and-TS_F_20210722%20(1).xlsx?web=1) on tab **_QA-Reqid 00012 - Req fields_**

QA: Data elements tested based on GenV2 with CDC Priority of R

Error message updates needed for
**OBR-25, 77991-8, 77992-6, 77966-0, 77990-0**

Postman Collection is **DEX Genv2- Required fields missingReqID 00012.postman_collection** [here](https://cdc.sharepoint.com/:f:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/Postman?csf=1&web=1&e=W9FSVT)

Linked to #510

![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/843a5421-026a-43d9-97e0-a3480dfd9fe7)

**Comment by mscaldas2012** [comment]
Decision: Messages will stay as is - It issues "ERRORS" for missing required fields
