### ISSUE TITLE
Define and document each step in ingest and validation pipeline

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#63]
Define/document each step in the ingest and validation pipeline where there is an action taken on the data.

**Comment by rmharrison** [comment]
@lmcnabb Rolled-over to next sprint. I don't understand the intent of the document well enough to accept.
- Option A: Companion to BPMN diagram, "Lucid > HL7v2 Case Notification Message Validation Flow"
- Option B: Companion to Azure function logical detail, "Lucid > Transport Component Interface > pipeline"
- Option C: Notification/Comms plan by failure mode

**Comment by mscaldas2012** [comment]
I believe having diagrams can be beneficial - but the intent audience is for non-tech folks, so need to keep diagrams at High Level. 
the intent should be to describe in enough detail all we're doing to the message, what's the output, where are we deviating from current (MVPS) implementations.
