### ISSUE TITLE
GENv2 HL7 Validations: Blanket Processing: Req ID 00025 - Update the error message for the 2nd repetition of MSH-21 

### ISSUE THREAD

**Issue by nadiackhan** [CDCgov/data-exchange-hl7#632]
Reference document: [NND Requirements](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/NND%20Requirements%20Implementation%20Matrix%20-%202022-12-16%20DEX.xlsx?web=1)
TAB: **Blanket Processing**
REQ ID: **00025**
QA TEST RESULTS [HERE](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/QA%20Validation%20of%20Generic_V2_0_1_MMG-and-TS_F_20210722%20(1).xlsx?web=1) on tab **QA-Reqid00025 MSH-21 Validations**
**Postman Collection**  -  **DEX Genv2- Required fields missingReqID 00012.postman_collection** [here](https://cdc.sharepoint.com/:f:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Development/QA/Postman?csf=1&web=1&e=4JTOv3)

1. Send a HL7 message where MSH-21 Reptition 2 is missing
2. Verify that the following error message is returned: 
**An unsupported literal value was provided for the Message Profile Identifier (NOT115, MSH-21). Replace the unsupported literal value with the required literal value as defined in the conformance statement within the current version of the PHIN Messaging Guide for Case Notification Reporting and the appropriate Message Mapping Guide.**

**Actual Result:** The following error is returned - see [here](https://cdc.sharepoint.com/teams/CDC-Data-Exchange/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FCDC%2DData%2DExchange%2FShared%20Documents%2FBuild%20%2D%20HL7%2FDevelopment%2FQA%2FPOSTMAN%20TEST%20RESULTS%2FReqID%2000025%20Genv2%20%2D%20MSH%2D21%20%2D%20second%20repetition%20missing%20TEST%20RESULT%2Etxt&parent=%2Fteams%2FCDC%2DData%2DExchange%2FShared%20Documents%2FBuild%20%2D%20HL7%2FDevelopment%2FQA%2FPOSTMAN%20TEST%20RESULTS)

**Expected Result:** The following error should be displayed as it is for MVPS
**An unsupported literal value was provided for the Message Profile Identifier (NOT115, MSH-21). Replace the unsupported literal value with the required literal value as defined in the conformance statement within the current version of the PHIN Messaging Guide for Case Notification Reporting and the appropriate Message Mapping Guide.**

**Comment by nadiackhan** [comment]
Please determine whether this should be considered a bug or enhancement @lmcnabb  @manandappa

**Comment by mscaldas2012** [comment]
Decision - Error message stays as is. Stacktrace information is not pushed to customers
