### ISSUE TITLE
Need add the cloud groups to ZScalar Firewall

### ISSUE THREAD

**Issue by ucf4** [CDCgov/data-exchange-hl7#639]
Please add these below groups to the ZScalar Firewall.

Groups list:
1. gp-u-dex-celr-developer-dev
2. gp-u-dex-celr-developer-tst
3. gp-u-dex-celr-developer-stg
4. gp-u-dex-celr-developer-prd

**Comment by ucf4** [comment]
Sent the email to the Firewall team in order to add the groups to ZScalar Firewall.

**Comment by ucf4** [comment]
Raised firewall request "C75511".

**Comment by ucf4** [comment]
I have received update from the Firewall team saying that they are not able to allow the Cloud group for the CDC Internal firewall rules. So I have raised another request for the AD Windows group to the Cloud team and added task #677

**Comment by ucf4** [comment]
As per the update the firewall request has been completed and also assigned Zscalar permissions to the groups as well. 

@uil9 @ugx2 @guntukuhari  Please validate the access.

**Comment by uil9** [comment]
I was able to run the tests without zscaler blocking connection to Azure.
