### ISSUE TITLE
Document MMG Validation, including triggers for errors and warnings

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#64]
As a program or STLT, I need to understand what will trigger an error or warning during the MMG validation step.  This information should be documented in an artifact that can be shared with customers.

**Comment by lmcnabb** [comment]
![image.png](https://images.zenhubusercontent.com/6230a6db53509272f2ac9e4b/6344c630-eea3-46f6-a05f-63a4a695a8c1)[https://app.zenhub.com/files/510836864/4bdae919-b518-4920-a6e0-b9f314151f71/download](https://app.zenhub.com/files/510836864/4bdae919-b518-4920-a6e0-b9f314151f71/download)

**Comment by marcia-schulman** [comment]
QED per the image posted by Leslyn
