### ISSUE TITLE
Hepatitis Program requested to populate more data for all of their conditions.

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#646]
Hepatitis program requested that they would like to see more data in their views. Currently their view contains only one message duplicated multiple times.

**Comment by mscaldas2012** [comment]
Please provide location of data and we will load it.

**Comment by mscaldas2012** [comment]
https://cdc.sharepoint.com/:u:/r/teams/CDC-Data-Exchange/Shared%20Documents/Pilot%20-%20HL7%20(Lyme,%20Arbo,%20Hepatitis)/Hepatitis/Hepatitis%20Test%20Messages/Prod%20Test%20Messages/Hepatitis%20Lab%20Template%20Errors%20Warnings.zip?csf=1&web=1&e=ouwf3n

**Comment by lmcnabb** [comment]
@dtx0111 put an estimate on this one for me
