### ISSUE TITLE
Hepatitis program would like run python code against databricks

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#647]
We need to provide a dev env to have access to MMG model and MMG in SQL model

**Comment by mscaldas2012** [comment]
programs need to request workspace access to EDAV.

The workspace needs to have access to our Database -  ocio_dex_prog_dev

**Comment by raman-cdc** [comment]
Databricks cluster "DEX_DEV_HEP_Cluster_AD_ACLs_Disabled" created for HEP team 
gp-u-EDAV-DEX-HEPATITIS-DBR-DEVELOPER group added to above cluster 

They can use Daatbricks Data Science and engineering workbench to run python jobs
