### ISSUE TITLE
Document PID and NK fields that we are going to redact in Redaction Service

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#65]
As a STLT or program user, I would like to know which PID and NK fields that DEX will be redacting and how redaction will occur.  I need to be able to read an artifact to understand the redaction service.  Assume this artifact will live separately and be referenced by a document entitled "Data Exchange validation and provisioning.docx"

**Comment by rmharrison** [comment]
PD, NK and ZLR segments included in ADR (Architecture Decision Record)
[DEX-ADR HL7v2 Redaction.docx](https://cdc.sharepoint.com/:w:/r/teams/CDC-Data-Exchange/_layouts/15/Doc.aspx?sourcedoc=%7B3160AA76-CA20-4B55-8BE2-5A9EC0B3ED49%7D&file=DEX-ADR%20HL7v2%20Redaction.docx)
