### ISSUE TITLE
Update lib-bumblebee

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#681]
- [ ] repackaged to gov.cdc.dex
- [ ] Upgrade dependencies
- [ ] Deploy to to imagehub.cdc.gov

**Comment by uhc7** [comment]
Repackaging done.
Updated all dependencies.

**Comment by uhc7** [comment]
Deployed to imagehub.cdc.gov - Done

**Comment by uhc7** [comment]
Deployed URL:
https://imagehub.cdc.gov/#browse/browse:maven-ede-snapshot:gov%2Fcdc%2Fdex%2Flib-bumblebee%2F1.0.0-SNAPSHOT
