### ISSUE TITLE
Redactor: Build Redactor Service for HL7 processing pipeline

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#70]
DEX needs a redaction service that will serve multiple HL7 data streams, with varying needs for redaction.  We envision this to be a config file that stores the needed redaction fields and actions for each use case.  The first use case for the redaction service is case notification messages.  For case notification messages, we would use the redaction service to remove specific segments that contain known PII so that this data would not be passed down to the program during provisioning.  

Specific segments:
PII can reside in the PID and NK segments in case notification messages that we receive.  Some PID and NK segments are requested in case messages by NNDSS but some are not and contain highly sensitive PII.  These should be redacted if accidentally sent by a STLT.  This data, if present at the time when it is processed through the NIST validator, will error due to the PHIN Spec.  Adjustments will be need to be made to the PHIN Spec to allow redacted info to flow through it.  The specific fields that require redaction are:

Action to be taken by the redactor:
If any segment in the above list is populated, we will remove it and replace the content with the word "REDACTED by DEX" This will convey to the data user downstream that the original message contained PII and that DEX removed it.  The redaction service will then pass on to the next service this redacted message, instead of the original one supplied to the redactor service.

We will need to surface redacted information through a GUI, along with associated metadata, so we will need a way to store/link the redacted information type (e.g., PID-5) along with the original raw message, combined with sender info, date/time sent.  The receiver of this information would use it to trace/fix a message that contains PII or OBX/OBR that shouldn't be present in the message.  The actual content in the field does not need to be kept for a GUI, just the ability for the sender of the message to link to the raw message if the original message needs to be examined.

Future work/idea for redaction (documented here, but not required):
ML algorithm to search inside Z segments or free text fields for PII for the case notification use case.

Decision point that deviates from current processes in NNDSS:  Data Exchange will NOT remove extraneous OBX and OBR segments that a jurisdiction sends in as a general rule (e.g., segments not defined in the MMG).

**Comment by rmharrison** [comment]
Input
- HL7v2 message from EventHub
- Redaction Config

Output
- HL7v2 message (redacted)
- Record of what was redacted in separate file

**Comment by rmharrison** [comment]
Goal: Provide a redactor service for both Case and ELR Validation pipelines

Function sequence
1. Receiver-Debatcher
2. **Redactor** (new)
3. Structure Validator

2022-12-21
1. Team examines current HL7-PET vs ELR Redaction implementation
2. Decide to choose 1 implementation or merge the implementation
3. Implement the redactor
3a. App Dev
3.b Ops (rewire pipeline: create the function + create the EventHubs)
