### ISSUE TITLE
DEX write to "EDAV > StorageAccount > ADLS" for DEV

### ISSUE THREAD

**Issue by rmharrison** [CDCgov/data-exchange-hl7#71]

**Comment by rmharrison** [comment]
## "Initial" (the scope of this issue) 
For demonstration of HL7v2 processing pipeline to Arbo business team in September 2022
EDX ADLS will PUSH to EDAV ADLS

From EDX
- [ ] Setup private ADLS? endpoint within EDX

From EDAV
- [ ] Send onboarding/intake form

Unsorted
- [ ] Location / Folder structure 
- [ ] Service Principle for access 
- [ ] Subnet ranges of write-mechanism (Databricks cluster) 

## Meetings
- [X] 2022-09-01: EDAV and EDX team agree to "EDAV-1" path for Sep 2022 demo, EDX ADLS will PUSH to EDAV ADLS

## Placeholder for out of scope items
"EDAV-2" flow: EDX EventHub --> EDAV EventHub --> EDAV ADLS

**Comment by boris-ning-usds** [comment]
We haven't gotten a new storage account yet, but they did give us access to their storage account which I'm creating a private endpoint to.

**Comment by raman-cdc** [comment]
Used AZcopy command to copy data from Desktop to ADLS BLOB storage 

-    Verified access to common ADLS BLOB Storage / Container  using azcopy command and from Portal
-    Verified access to DEX ADLS BLOB Storage / Container  using azcopy command and from Portal.
-

**Comment by raman-cdc** [comment]
Validated using AZCopy and SAS token
