### ISSUE TITLE
hl7_structure_silver is returning duplicate records on DEV

### ISSUE THREAD

**Issue by nadiackhan** [CDCgov/data-exchange-hl7#724]
hl7_structure_silver is returning duplicate records on DEV

Query: 
**Select * 
FROM hive_metastore.ocio_dex_dev.hl7_structure_silver -- order by provenance.file_timestamp desc
where provenance.ext_original_file_name like '%4899ba3b-4662-4d86-96a0-be297290cbef%'** 

![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/683d01ab-9a88-453f-ac7e-b84f1c39ec32)

**Comment by mscaldas2012** [comment]
Lets try to replicate this in TEST to validate is an actual bug and not some local function running on developers machine concurrently to the cloud function - processing the Event hub twice.

**Comment by nadiackhan** [comment]
Validated in Test. Records are not duplicated. 

![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/54ee98da-ca5d-461e-b921-9f9fffd1d3db)
