### ISSUE TITLE
Update Structure validator to use different Event Hubs for CASE vs ELR messages

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#736]
We need to separate case messages from ELR messages on Structure Validator, so that the MMG Validator gets only Case messages (ERL do not follow MMG paradigm).

Need new Event hub to receive good ELR messages. (ELR messages that fails Structure validator can be combined with failed case messages on structure err Event Hub.)

![image.png](https://images.zenhubusercontent.com/62fe6e64b6093409a06fd538/bd8f96ea-3073-4033-a97d-c5bf47567ff7)

**Comment by nadiackhan** [comment]
Validated. 
Adding the following to the header I am able to validate the messages on the structure validator. 
x-tp-message_type - CASE or ELR
x-tp-route - COVID19_ELR
![image.png](https://images.zenhubusercontent.com/63daba99ae9e054f0b7aefb2/b72ef8c3-7a54-4c88-bf48-a4c134b1bf95)
