### ISSUE TITLE
Research on how to unit test the Azure function

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#780]
we have unit test for pieces of logic, but I don't know how to call the actual function from a unit test and execute its entirety.
hopefully mocking the event hubs so we don't post anything to the actual pipeline.

Extra:
also, there's a way to call a function via HTTP endpoint 
ex.: https://{{CACHE_LOADER_URL}}/admin/functions/PhinVocabRead

I've been using that for our cache loader functions that do not expect any payload on the HTTP body.

I'd like to learn how to call our az functions that are event hub bound - how does the body needs to be constructed so we can execute it like that...

**Comment by uil9** [comment]
Using POSTMAN, we could trigger EventGrid, Blob, HTTP trigger based functions, but was unable to find for EventHub based Azure functions.
For getting metadata information of a function, we could make GET call to - http://localhost:7071/admin/functions/{functionName}

**Comment by uil9** [comment]
This is the POST request for calling the EventHub Trigger based function -

curl --location '[http://localhost:7071/admin/functions/Redactor'](http://localhost:7071/admin/functions/Redactor%27) \

--header 'Content-Type: application/json' \

--data '{"input": "{\\"msg\\":{},\\"message\\":{},\\"msg\\":{},\\"context\\":{}}"}'


But receiving this error - [2023-04-12T15:39:23.799Z] System.Private.CoreLib: Exception while executing function: Functions.Redactor. System.Private.CoreLib: Result: Failure
Exception: RuntimeException: Cannot find matched @BindingName of customer function, please check if customer function is defined correctly
Stack: java.lang.RuntimeException: Cannot find matched @BindingName of customer function, please check if customer function is defined correctly
