### ISSUE TITLE
Move PHINMS feed from Azure devops repo to our Github

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#801]
right now, we're having some issues connecting our EDAV datafactory that pulls data from phinms into our Az storage accounts to be linked with our github,

Temporarily, the datafactory is hooked to https://dev.azure.com/xlr-team/cs-pipeline/_git/phinms-feed

We would like to migrate that to our github repo under cdcgov/data-exchange-hl7

**Comment by mscaldas2012** [comment]
I've sent an initial email to Ravi (Mettupalli, Ravindra (CDC/OCOO/OCIO/DSO) (CTR) <bcv7@cdc.gov>) and awaiting resonse

**Comment by ssk2cdcgov** [comment]
This should be done. Just need to review some details, about folders.
