### ISSUE TITLE
Add Azure monitoring metrics for PHIN VOCAB Service

### ISSUE THREAD

**Issue by dtx0111** [CDCgov/data-exchange-hl7#81]
add metrics of phin-vocab fn for below listed items,
- Refresh execution started
- Refresh execution ended (total time / total keys created)

**Comment by mscaldas2012** [comment]
see this - https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

if using log4j or java.utils.logging, it seems will be automatically collected!
