### ISSUE TITLE
IGAMT Validator: Build out PHIN Spec versions and MMGs into IGAMT

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#85]
For Phase II use cases - this includes, Lyme/TBRD, Arboviral, and Viral Hepatitis

**Comment by rmharrison** [comment]
Status as of 2022-09-16
| Status | IGAMT profiles | Note | 
|--------|------------------|-----|
| Done  | PHIN Spec 2.0 |
| Done  | PHIN Spec 3.0 |
| Done  | PHIN Spec 3.1 |
| Not Done  | PHIN Spec 3.2 |
| ? |  GenV1 (Individual case report) | 
| ? |  GenV1-Summary (Summary of one individual) | 
| ? | VXU | 
| N/A | ELR | Should reuse PHINSpec IGAMT profiles; MMGAT JSON does not support
| N/A | GenV2 | Validated with MMGAT, not IGAMT
| N/A | GenV2-based condition-specific MMGs | Validated with MMGAT, not IGAMT

Legend
?: Status unknown
N/A: Not Applicable.
