### ISSUE TITLE
REDACTOR: Create unit test for the Function method and add Coverage report

### ISSUE THREAD

**Issue by mscaldas2012** [CDCgov/data-exchange-hl7#886]
Create unit tests calling the actual function method for the Redactor function.
Make sure all paths are being called.
Add JaCoCo for coverage report and try to achieve 80% coverage.
Include assertions when possible. (at a minimum, assert(true) at the end of the unit test to make sure the full test was executed)

**Comment by uil9** [comment]
![image.png](https://images.zenhubusercontent.com/63e265d1c555093dc45e5e13/36ea5107-86af-4e23-aadb-a068aef3f690)
