### ISSUE TITLE
SPIKE Pipeline GUI for Devs: Prototype internal team-facing dashboard using Grafana

### ISSUE THREAD

**Issue by lmcnabb** [CDCgov/data-exchange-hl7#89]
Explore using Grafana for an internal team-facing dashboard that can be used to look at the health of the validation pipeline and functioning of validation processing.

Closing this issue because Fearless will tackle an internal-facing DEX status dashboard for the functioning of the pipelines.

**Comment by RuDue** [comment]
@lmcnabb Relabeled for Roadmap.   Please review confirm and advise.
