### ISSUE TITLE
Sprint Goal: 8-21 Sept 2022

### ISSUE THREAD

**Issue by dcdlz** [CDCgov/data-exchange-hl7#90]
NB: This is a hack because Sprint Goals are not supported by ZenHub.
"Official" proposal of this hack from ZenHub: https://www.youtube.com/watch?v=S_yzDz3rHCI

Sprint Planning: 8 September 2022

1. **Structure Validator                          <~~~ Achieved**
2. Create the Lake of Segments
  - Included: MSH, PID, OBR, OBX
  - Not included: VXU	
3. **MMG-based model, phase 1        <~~~ Sprint Goal**
  - Req: MMG Service
4. MMG-based model, phase 2
  - Req: Vocab Service

Out of scope for Sprint
- Redactor
- Lab template
- Repeating MMG Model segments in a different table

**Comment by rmharrison** [comment]
FFR: Sprint goal was a bit too aggressive with a quarterly planning meeting and a bunch of interface meetings.
