### ISSUE TITLE
Connecting Grafana to Azure Databricks 

### ISSUE THREAD

**Issue by raman-cdc** [CDCgov/data-exchange-hl7#92]
Current version of Azure managed Grafana does not support Databricks Plugin and is available only in enterprise version.

Microsoft is planning on changing this next month and including this feature in Azure Managed Grafana.

**Comment by raman-cdc** [comment]
Current Version of Azure Managed Grafana does not allow you to install Plugin for Databricks.

Although it shows in the UI, you will not be able to install this plugin. Overall, Azure Managed Grafana doesn't allow users to install or uninstall plugins right now, they can only use what's already installed.

Azure Product Team is  planning on changing this next month and including this feature.

**Comment by rmharrison** [comment]
Status, end of Sprint 22 Sep - 5 Oct: Waiting for Microsoft to include support.
@raman-cdc Please monitor. In the meanwhile, moved to Icebox.
