### ISSUE TITLE
Conduct discovery around how to add PHLIP Flu and VPD messages to HL7 Pipeline

### ISSUE THREAD

**Issue by manandappa** [CDCgov/data-exchange-hl7#968]
- [ ] Specs can be found
https://cdc.sharepoint.com/:w:/r/teams/CDC-Data-Exchange/Shared%20Documents/Pilot%20-%20HL7%20ELR%20(PHLIP)/Specs/PHLIP%20Message%20Elements%20231%20and%20251.docx?d=webebed5946d84d7ebc16f1e54baacc52&csf=1&web=1&e=KhEXac

**Comment by marcia-schulman** [comment]
Important info [here](https://cdc.sharepoint.com/:f:/r/teams/CDC-Data-Exchange/Shared%20Documents/Build%20-%20HL7/Case/PHLIP%20Flu%20and%20VPD?csf=1&web=1&e=aSFeEo)

**Comment by marcia-schulman** [comment]
Meeting scheduled for 6/1/23 to discuss data product requirements.
